<?php

$monster_data = [["-89", "Count Drunkula (Hard Mode)", "undead"],
["-88", "Falls-From-Sky (Hard Mode)", "beast"],
["-87", "Great Wolf of the Air (Hard Mode)", "beast"],
["-86", "Mayor Ghost (Hard Mode)", "undead"],
["-85", "The Unkillable Skeleton (Hard Mode)", "undead"],
["-84", "Zombie Homeowners' Association (Hard Mode)", "undead"],
["-37", "Slime", "slime"],
["-36", "Slime Hand", "slime"],
["-35", "Slime Mouth", "slime"],
["-34", "Slime Construct", "slime"],
["-33", "Slime Colossus", "slime"],
["-31", "intelligent alien", "humanoid"],
["-30", "Guajolote Cad&aacute;ver", "undead"],
["-29", "Peregrino Cad&aacute;ver", "undead"],
["-28", "T&iacute;o Cad&aacute;ver", "undead"],
["0", "ancient protector spirit", "undead"],
["1", "spooky vampire (Spooky Forest)", "undead"],
["3", "dodecapede", "bug"],
["5", "apathetic lizardman", "humanoid"],
["9", "Gnollish Plungermaster", "humanoid"],
["11", "Gnollish Flyslayer", "humanoid"],
["12", "Gnollish Gearhead", "humanoid"],
["13", "Gnollish Bodybuilder", "humanoid"],
["17", "Gnollish Sorceress", "humanoid"],
["18", "one-eyed Gnoll", "humanoid"],
["19", "Gnollish Crossdresser", "humanoid"],
["20", "Gnollish Tirejuggler", "humanoid"],
["21", "Gorgolok, the Infernal Seal (Inner Sanctum)", "demon"],
["22", "Stella, the Turtle Poacher (Inner Sanctum)", "dude"],
["23", "Spaghetti Elemental (Inner Sanctum)", "elemental"],
["24", "Lumpy, the Sinister Sauceblob (Inner Sanctum)", "slime"],
["25", "Spirit of New Wave (Inner Sanctum)", "undead"],
["26", "Somerset Lopez, Dread Mariachi (Inner Sanctum)", "dude"],
["27", "Gnollish Piebaker", "humanoid"],
["28", "Guard Bugbear", "beast"],
["29", "skleleton", "undead"],
["30", "ghuol", "undead"],
["31", "zmobie", "undead"],
["32", "lihc", "undead"],
["33", "zobmie", "undead"],
["34", "Brainsweeper", "construct"],
["35", "Bread Golem", "construct"],
["36", "Yeast Beast", "construct"],
["37", "Weretaco", "beast"],
["38", "giant pair of tweezers", "construct"],
["39", "Chowder Golem", "construct"],
["40", "Smart Skelton", "undead"],
["41", "albino bat", "beast"],
["42", "doughbat", "beast"],
["43", "baseball bat", "beast"],
["44", "regular old bat", "beast"],
["45", "skullbat", "beast"],
["46", "briefcase bat", "beast"],
["47", "perpendicular bat", "beast"],
["48", "beanbat", "beast"],
["49", "Boss Bat", "beast"],
["51", "drunken rat", "beast"],
["52", "filthy hippy", "hippy"],
["53", "dirty hippy", "hippy"],
["54", "crusty hippy", "hippy"],
["55", "filthy hippy Vegan chef", "hippy"],
["56", "dirty hippy Vegan chef", "hippy"],
["57", "crusty hippy Vegan chef", "hippy"],
["58", "filthy hippy jewelry maker", "hippy"],
["59", "dirty hippy jewelry maker", "hippy"],
["60", "crusty hippy jewelry maker", "hippy"],
["61", "grave rober", "dude"],
["62", "Orcish Frat Boy (Music Lover)", "orc"],
["63", "Orcish Frat Boy (Paddler)", "orc"],
["64", "Orcish Frat Boy (Pledge)", "orc"],
["65", "whitesnake", "beast"],
["66", "white lion", "beast"],
["67", "white chocolate golem", "construct"],
["68", "Knight in White Satin", "dude"],
["69", "dairy ooze", "slime"],
["70", "sabre-toothed lime", "beast"],
["71", "pencil golem", "construct"],
["72", "giant giant moth", "bug"],
["73", "mayonnaise wasp", "bug"],
["74", "tonic water elemental", "elemental"],
["75", "vampire clam", "undead"],
["76", "Knob Goblin Sous Chef", "goblin"],
["77", "Knob Goblin Master Chef", "goblin"],
["78", "Knob Goblin Harem Girl", "goblin"],
["79", "Knob Goblin Elite Guardsman", "goblin"],
["80", "Knob Goblin Bean Counter", "goblin"],
["81", "Knob Goblin King", "goblin"],
["82", "drunk goat", "beast"],
["83", "dairy goat", "beast"],
["84", "sabre-toothed goat", "beast"],
["85", "Knob Goblin Mad Scientist", "goblin"],
["86", "Knob Goblin Very Mad Scientist", "goblin"],
["87", "BASIC Elemental", "elemental"],
["88", "Knob Goblin Mutant", "goblin"],
["89", "Fruit Golem", "construct"],
["90", "Grass Elemental", "elemental"],
["91", "Weremoose", "beast"],
["92", "Carnivorous Moxie Weed", "plant"],
["93", "Spectral Jellyfish", "beast"],
["94", "Portly Abomination", "horror"],
["95", "Booze Giant", "humanoid"],
["96", "7-Foot Dwarf (Royale)", "humanoid"],
["97", "7-Foot Dwarf (Moiling)", "humanoid"],
["98", "7-Foot Dwarf Foreman", "humanoid"],
["99", "Knott Yeti", "beast"],
["100", "Ninja Snowman (Mask)", "elemental"],
["104", "sassy pirate", "pirate"],
["105", "swarthy pirate", "pirate"],
["106", "smarmy pirate", "pirate"],
["107", "shady pirate", "pirate"],
["108", "bugbear-in-the-box", "beast"],
["109", "lemon-in-the-box", "construct"],
["110", "disease-in-the-box", "construct"],
["111", "scary clown", "horror"],
["112", "creepy clown", "horror"],
["113", "Goomba", "beast"],
["114", "Tektite", "beast"],
["116", "Koopa Troopa", "beast"],
["117", "Octorok", "beast"],
["118", "Blooper", "beast"],
["119", "Keese", "beast"],
["120", "Zol", "slime"],
["121", "Bullet Bill", "construct"],
["122", "W imp", "demon"],
["123", "P imp", "demon"],
["124", "L imp", "demon"],
["125", "G imp", "demon"],
["126", "Demoninja", "demon"],
["127", "Fallen Archfiend", "demon"],
["128", "Hellion", "demon"],
["129", "shifty pirate", "pirate"],
["130", "Drab Bard", "dude"],
["131", "Racecar Bob", "dude"],
["132", "Bob Racecar", "dude"],
["133", "Flock of Stab-bats", "beast"],
["134", "Taco Cat", "beast"],
["135", "Tan Gnat", "bug"],
["136", "Evil Olive", "beast"],
["137", "Ninja Snowman (Hilt)", "elemental"],
["138", "XXX pr0n", "beast"],
["139", "Anime Smiley", "horror"],
["140", "Lamz0r N00b", "dude"],
["141", "1335 HaXx0r", "dude"],
["142", "Flaming Troll", "humanoid"],
["143", "Spam Witch", "dude"],
["144", "me4t begZ0r", "dude"],
["145", "possessed can of tomatoes", "undead"],
["146", "fiendish can of asparagus", "undead"],
["147", "undead elbow macaroni (monster)", "undead"],
["148", "flame-broiled meat blob", "slime"],
["149", "pine bat", "beast"],
["150", "batrat", "beast"],
["151", "ratbat", "beast"],
["152", "sleeping Knob Goblin Guard", "goblin"],
["153", "Knob Goblin Assistant Chef", "goblin"],
["154", "Sub-Assistant Knob Mad Scientist", "goblin"],
["155", "Knob Goblin Barbecue Team", "goblin"],
["156", "big creepy spider", "bug"],
["157", "completely different spider", "bug"],
["158", "drunken half-orc hobo", "hobo"],
["159", "rushing bum", "hobo"],
["160", "Protagonist", "dude"],
["161", "Quiet Healer", "dude"],
["165", "Spunky Princess", "dude"],
["166", "Burly Sidekick", "dude"],
["167", "Irritating Series of Random Encounters", "beast"],
["170", "Procrastination Giant", "humanoid"],
["171", "Possibility Giant", "humanoid"],
["172", "Furry Giant", "humanoid"],
["173", "Raver Giant", "humanoid"],
["174", "Goth Giant", "humanoid"],
["175", "MagiMechTech MechaMech", "construct"],
["176", "Alphabet Giant", "humanoid"],
["177", "tiny barrel mimic", "weird"],
["178", "One-Eyed Willie", "constellation"],
["179", "Trouser Snake", "constellation"],
["180", "Family Jewels", "constellation"],
["181", "Junk", "constellation"],
["182", "Pork Sword", "constellation"],
["183", "Hooded Warrior", "constellation"],
["184", "Astronomer", "constellation"],
["185", "spiny skelelton", "undead"],
["186", "toothy sklelton", "undead"],
["187", "giant skeelton", "undead"],
["189", "gluttonous ghuol", "undead"],
["190", "gaunt ghuol", "undead"],
["191", "huge ghuol", "undead"],
["192", "senile lihc", "undead"],
["193", "slick lihc", "undead"],
["194", "gargantulihc", "undead"],
["195", "grave rober zmobie", "undead"],
["196", "corpulent zobmie", "undead"],
["197", "conjoined zmombie", "undead"],
["198", "Bonerdagon", "undead"],
["199", "warwelf", "dude"],
["200", "wolfman", "dude"],
["201", "spooky mummy", "undead"],
["202", "bar", "beast"],
["203", "Pretty Fly", "beast"],
["204", "Fickle Finger of F8", "weird"],
["205", "topiary golem", "plant"],
["206", "Flaming Samurai", "dude"],
["207", "Ice Cube", "elemental"],
["208", "Beer Batter", "construct"],
["209", "Enraged Cow", "beast"],
["210", "Shadow opponent", "dude"],
["211", "Gnollish War Chef", "humanoid"],
["213", "vine gar", "beast"],
["214", "ghostly pickle factory worker", "undead"],
["215", "carnivorous dill plant", "plant"],
["216", "Mob Penguin Pasta Chef", "penguin"],
["217", "Mob Penguin Thug", "penguin"],
["218", "Mob Penguin Soprano", "penguin"],
["219", "emaciated Knott Yeti", "beast"],
["220", "acid blob", "slime"],
["221", "swarm of killer bees", "bug"],
["222", "mind flayer", "horror"],
["223", "Quantum Mechanic", "dude"],
["224", "large kobold", "humanoid"],
["225", "poutine ooze", "slime"],
["226", "cloud of disembodied whiskers", "weird"],
["227", "axe handle", "construct"],
["228", "forest spirit", "undead"],
["229", "crazy bastard", "dude"],
["230", "infinite meat bug", "bug"],
["231", "Baiowulf", "dude"],
["232", "Hypnotist of Hey Deze", "dude"],
["233", "decent lumberjack", "dude"],
["234", "lumberjill", "dude"],
["235", "lumberjuan", "dude"],
["236", "lumberjack supervisor", "dude"],
["237", "X-headed Hydra", "beast"],
["238", "Ghost of Fernswarthy's Grandfather", "undead"],
["239", "Beast with X Eyes", "horror"],
["240", "Beast with X Ears", "horror"],
["241", "X Bottles of Beer on a Golem", "construct"],
["242", "X Stone Golem", "construct"],
["243", "Naughty Sorceress", "dude"],
["244", "Naughty Sorceress (2)", "dude"],
["245", "Naughty Sorceress (3)", "dude"],
["247", "vicious gnauga", "beast"],
["248", "gnasty gnome", "humanoid"],
["249", "gnarly gnome", "humanoid"],
["250", "gnu jack gnome", "humanoid"],
["251", "Gnomester Blomester", "humanoid"],
["252", "gnefarious gnome", "humanoid"],
["254", "revolting bugbear", "beast"],
["255", "revolving bugbear", "beast"],
["256", "angry bugbear", "beast"],
["257", "mad bugbears", "beast"],
["258", "bugged bugbear", "beast"],
["259", "annoying spooky gravy fairy", "plant"],
["260", "spooky gravy fairy guard", "plant"],
["261", "spooky gravy fairy warlock", "plant"],
["262", "spooky gravy fairy ninja", "plant"],
["263", "Knob Goblin Elite Guard Captain", "goblin"],
["266", "Felonia, Queen of the Spooky Gravy Fairies", "plant"],
["268", "irate mariachi", "dude"],
["269", "angry pi&ntilde;ata", "construct"],
["270", "handsome mariachi", "dude"],
["271", "raging bull", "dude"],
["272", "mariachi calavera", "undead"],
["273", "Buzzy Beetle", "bug"],
["274", "hockey elemental", "elemental"],
["275", "Vicious Easel", "construct"],
["276", "Big Meat Golem", "construct"],
["277", "Bowling Cricket", "bug"],
["278", "Tyrannosaurus Tex", "beast"],
["279", "Giant Desktop Globe", "construct"],
["280", "Electron Submarine", "construct"],
["281", "hung-over half-orc hobo", "hobo"],
["282", "overdone flame-broiled meat blob", "slime"],
["283", "mimic (Cloak)", "weird"],
["284", "Lesser Fruit Golem", "construct"],
["285", "shaky clown", "horror"],
["286", "Baron von Ratsworth", "beast"],
["287", "small barrel mimic", "weird"],
["288", "medium-sized barrel mimic", "weird"],
["289", "huge barrel mimic", "weird"],
["290", "Dyspepsi-Cola Soldier", "dude"],
["291", "Dyspepsi-Cola Knight", "dude"],
["292", "Cloaca-Cola Soldier", "dude"],
["293", "Dyspepsi-Cola General", "dude"],
["294", "Cloaca-Cola Footsoldier", "dude"],
["295", "Cloaca-Cola Catapult Engineer", "dude"],
["296", "drunken zombie half-orc hobo", "undead"],
["297", "fiendish zombie can of asparagus", "undead"],
["298", "zombie apathetic lizardman", "undead"],
["299", "Zombie Knob Goblin Assistant Chef", "goblin"],
["300", "Knob Goblin Elite Zombie", "goblin"],
["301", "zombie Gnollish crossdresser", "humanoid"],
["302", "Zombie Clown", "horror"],
["303", "zombie zmobie", "undead"],
["304", "zombie yeast beast", "undead"],
["305", "zombie frat boy", "orc"],
["306", "zombie hippy", "hippy"],
["307", "scary pirate (cursed)", "pirate"],
["308", "white zombie", "undead"],
["309", "Zombie N00b", "undead"],
["310", "Zombie eXtreme Snowboarding Orc", "undead"],
["311", "Zombie Quiet Healer", "undead"],
["312", "Zombie Goth Giant", "undead"],
["313", "fluffy bunny", "beast"],
["314", "Malevolent Tofurkey", "beast"],
["315", "Stuffing Golem", "construct"],
["316", "Possessed Can of Cranberry Sauce", "undead"],
["317", "Candied Yam Golem", "construct"],
["318", "Striking Factory-Worker Elf", "elf"],
["319", "Striking Middle-Management Elf", "elf"],
["320", "Striking Pencil-Pusher Elf", "elf"],
["321", "Striking Stocking-Stuffer Elf", "elf"],
["322", "Striking Gift-Wrapper Elf", "elf"],
["323", "Rudolph the Red (Monster)", "beast"],
["324", "Dopey, the Reindeer", "beast"],
["325", "Sleepy, the Reindeer", "beast"],
["326", "Happy, the Reindeer", "beast"],
["327", "Bashful, the Reindeer", "beast"],
["328", "Grumpy, the Reindeer", "beast"],
["329", "Doc, the Reindeer", "beast"],
["330", "Sneezy, the Reindeer", "beast"],
["331", "Zeppo, the Reindeer", "beast"],
["332", "frog", "beast"],
["333", "newt", "beast"],
["334", "salamander", "beast"],
["335", "business hippy", "hippy"],
["336", "eXtreme Sports Orcs", "orc"],
["337", "angry raccoon puppet", "construct"],
["338", "Ninja Snowman (Chopsticks)", "elemental"],
["339", "Ninja Snowman Janitor", "elemental"],
["340", "Ninja Snowman Weaponmaster", "elemental"],
["342", "triffid", "plant"],
["348", "Count Bakula", "dude"],
["350", "vampire bat", "beast"],
["351", "Burrowing Bishop", "constellation"],
["352", "Twig and Berries", "constellation"],
["353", "Skinflute", "constellation"],
["354", "Astronomer", "constellation"],
["355", "Trippy Floating Head (Mona Lisa)", "weird"],
["356", "Trippy Floating Head (Casey Kasem)", "weird"],
["357", "Trippy Floating Head (Grand Moff Tarkin)", "weird"],
["358", "Zombie Baby", "undead"],
["359", "Swarm of Country Bats", "beast"],
["360", "Urge to Stare at Your Hands", "weird"],
["361", "Really Interesting Wallpaper", "weird"],
["362", "Visible Music", "weird"],
["363", "Feeling That You're Being Watched", "weird"],
["364", "Best Carpet Ever", "weird"],
["365", "Angels of Avalon", "weird"],
["366", "Bustle in the Hedgerow", "weird"],
["367", "Gathering of Angels?", "weird"],
["368", "Higher Plane Serpents", "weird"],
["369", "Elders of the Gentle Race", "weird"],
["370", "ghost miner", "undead"],
["371", "The Master Of Thieves", "dude"],
["372", "possessed silverware drawer", "undead"],
["373", "demonic icebox", "demon"],
["374", "paper towelgeist", "undead"],
["375", "skeletal hamster", "undead"],
["376", "confused goth music student", "dude"],
["377", "skullery maid", "undead"],
["378", "zombie chef", "undead"],
["379", "skeletal cat", "undead"],
["380", "skeletal monkey", "undead"],
["381", "anglerbush", "plant"],
["382", "man-eating plant", "plant"],
["383", "chalkdust wraith", "undead"],
["384", "upgraded ram", "beast"],
["385", "Snow Queen", "elemental"],
["386", "pooltergeist", "undead"],
["387", "bookbat", "construct"],
["388", "banshee librarian", "undead"],
["389", "malevolent hair clog", "horror"],
["390", "toilet papergeist", "undead"],
["391", "animated nightstand (White)", "construct"],
["392", "The Temporal Bandit", "dude"],
["393", "cubist bull", "beast"],
["394", "guy with a pitchfork, and his wife", "dude"],
["395", "empty suit of armor", "construct"],
["396", "remains of a jilted mistress", "undead"],
["397", "knight (Wolf)", "dude"],
["398", "knight (Snake)", "dude"],
["399", "animated nightstand (Mahogany)", "construct"],
["400", "claw-foot bathtub", "construct"],
["401", "zombie waltzers", "undead"],
["402", "tapdancing skeleton", "undead"],
["403", "ghastly organist", "undead"],
["404", "floating platter of hors d'oeuvres", "construct"],
["405", "writing desk", "construct"],
["406", "animated nightstand (White)", "construct"],
["407", "animated nightstand (Mahogany)", "construct"],
["408", "Skelter Butleton, the Butler Skeleton", "undead"],
["409", "Orcish Frat Boy Spy", "orc"],
["410", "War Hippy Dread Squad", "hippy"],
["411", "War Hippy Infantryman", "hippy"],
["412", "War Hippy Sky Captain", "hippy"],
["413", "War Hippy Fire Spinner", "hippy"],
["414", "black adder", "beast"],
["415", "black widow", "bug"],
["416", "black panther", "beast"],
["417", "Black Knight", "dude"],
["418", "blackberry bush", "plant"],
["419", "War Hippy Spy", "hippy"],
["420", "War Frat Kegrider", "orc"],
["421", "Panty Raider Frat Boy", "orc"],
["422", "Beer Bongadier", "orc"],
["423", "War Frat 151st Infantryman", "orc"],
["424", "Guy Made Of Bees", "horror"],
["425", "pooltergeist (Ultra-Rare)", "undead"],
["426", "Bad ASCII Art", "construct"],
["427", "flint-scraping cave elf", "elf"],
["428", "rock-banging cave elf", "elf"],
["429", "sinew-stretching cave elf", "elf"],
["430", "hunter-gatherer cave elf", "elf"],
["431", "skeletal reindeer", "undead"],
["432", "gift-wrapping vampire", "undead"],
["433", "stocking-stuffing zombie", "undead"],
["434", "bow-making mummy", "undead"],
["435", "Cookie-baking Thing from Beyond Time", "horror"],
["436", "toy-making creature from the Gray Lagoon", "undead"],
["437", "Ribbon-Cutting Elfborg", "construct"],
["438", "Arc-Welding Elfborg", "construct"],
["439", "Weapons-Assembly Elfborg", "construct"],
["440", "Decal-Applying Elfborg", "construct"],
["441", "Rudolphus of Crimborg", "construct"],
["442", "ancient protector spirit (The Hidden Apartment Building)", "undead"],
["443", "ancient protector spirit (The Hidden Hospital)", "undead"],
["444", "ancient protector spirit (The Hidden Office Building)", "undead"],
["445", "ancient protector spirit (The Hidden Bowling Alley)", "undead"],
["446", "ancient protector spirit", "undead"],
["447", "pygmy headhunter", "dude"],
["448", "pygmy assault squad", "dude"],
["449", "pygmy blowgunner", "dude"],
["450", "Protector Spectre", "undead"],
["451", "caveman frat boy", "orc"],
["452", "caveman sorority girl", "orc"],
["453", "Dr. Awkward", "dude"],
["454", "possessed wine rack", "construct"],
["455", "skeletal sommelier", "undead"],
["456", "swarm of scarab beatles", "bug"],
["457", "plaque of locusts", "bug"],
["458", "giant sandworm", "bug"],
["459", "oasis monster", "elemental"],
["460", "blur", "dude"],
["461", "swarm of fire ants", "bug"],
["462", "giant giant giant centipede", "bug"],
["463", "rock scorpion", "bug"],
["464", "Lord Spookyraven", "undead"],
["465", "cactuary", "plant"],
["467", "tomb rat", "beast"],
["468", "tomb servant", "undead"],
["469", "tomb asp", "beast"],
["470", "caveman frat pledge", "orc"],
["471", "caveman hippy", "hippy"],
["472", "cavewomyn hippy", "hippy"],
["473", "Ed the Undying", "undead"],
["473", "Ed the Undying (7)", "undead"],
["473", "Ed the Undying (6)", "undead"],
["473", "Ed the Undying (5)", "undead"],
["473", "Ed the Undying (4)", "undead"],
["473", "Ed the Undying (3)", "undead"],
["473", "Ed the Undying (2)", "undead"],
["473", "Ed the Undying (1)", "undead"],
["474", "sabre-toothed ferret", "beast"],
["475", "dirty thieving brigand", "dude"],
["476", "black pudding", "slime"],
["477", "larval filthworm", "bug"],
["478", "filthworm drone", "bug"],
["479", "filthworm royal guard", "bug"],
["480", "queen filthworm", "bug"],
["481", "War Hippy (space) cadet", "hippy"],
["482", "War Hippy drill sergeant", "hippy"],
["483", "War Hippy Baker", "hippy"],
["484", "War Hippy Rigger", "hippy"],
["485", "War Hippy F.R.O.G.", "hippy"],
["486", "War Hippy Green Gourmet", "hippy"],
["487", "War Hippy Elite Rigger", "hippy"],
["488", "Mobile Armored Sweat Lodge", "hippy"],
["489", "War Hippy Airborne Commander", "hippy"],
["490", "War Hippy Homeopath", "hippy"],
["491", "War Hippy Naturopathic Homeopath", "hippy"],
["492", "Green Ops Soldier", "hippy"],
["493", "War Hippy Windtalker", "hippy"],
["494", "War Hippy Shaman", "hippy"],
["495", "War Hippy Elder Shaman", "hippy"],
["496", "War Hippy Elite Fire Spinner", "hippy"],
["497", "War Frat 500th Infantrygentleman", "orc"],
["498", "War Frat 110th Infantryman", "orc"],
["499", "War Frat 151st Captain", "orc"],
["500", "War Frat Elite 500th Captain", "orc"],
["501", "War Frat Elite 110th Captain", "orc"],
["502", "War Frat Grill Sergeant", "orc"],
["503", "War Frat Senior Grill Sergeant", "orc"],
["504", "Heavy Kegtank", "orc"],
["505", "War Frat Wartender", "orc"],
["506", "War Frat Elite Wartender", "orc"],
["507", "Elite Beer Bongadier", "orc"],
["508", "Sorority Nurse", "orc"],
["509", "Sorority Operator", "orc"],
["510", "Naughty Sorority Nurse", "orc"],
["511", "Slow Talkin' Elliot", "hippy"],
["512", "Neil", "hippy"],
["513", "Zim Merman", "hippy"],
["514", "C.A.R.N.I.V.O.R.E. Operative", "hippy"],
["515", "Glass of Orange Juice", "hippy"],
["516", "Next-generation Frat Boy", "orc"],
["517", "Monty Basingstoke-Pratt, IV", "orc"],
["518", "Brutus, the toga-clad lout", "orc"],
["519", "Danglin' Chad", "orc"],
["520", "War Frat Streaker", "orc"],
["527", "War Pledge", "orc"],
["528", "Frat Warrior drill sergeant", "orc"],
["529", "lobsterfrogman", "beast"],
["530", "Knob Goblin Embezzler", "goblin"],
["531", "ferocious bugbear", "beast"],
["532", "gelatinous cube", "slime"],
["533", "Knob Goblin poseur", "goblin"],
["534", "ancient insane monk", "dude"],
["535", "Box", "constellation"],
["536", "Muff", "constellation"],
["537", "Bush", "constellation"],
["538", "Flange", "constellation"],
["539", "Beaver", "constellation"],
["540", "Little Man in the Canoe", "constellation"],
["541", "Camel's Toe", "constellation"],
["542", "Honey Pot", "constellation"],
["543", "Axe Wound", "constellation"],
["544", "generic duck", "beast"],
["545", "The Big Wisniewski", "hippy"],
["546", "erudite gremlin", "humanoid"],
["547", "erudite gremlin (quest)", "humanoid"],
["548", "batwinged gremlin", "humanoid"],
["549", "batwinged gremlin (quest)", "humanoid"],
["550", "vegetable gremlin", "humanoid"],
["551", "vegetable gremlin (quest)", "humanoid"],
["552", "spider gremlin", "humanoid"],
["553", "spider gremlin (quest)", "humanoid"],
["554", "A.M.C. gremlin", "humanoid"],
["555", "The Man", "dude"],
["556", "frozen duck", "beast"],
["557", "figure-skating duck", "beast"],
["558", "scorched duck", "beast"],
["559", "fire-breathing duck", "beast"],
["560", "greasy duck", "beast"],
["561", "rotund duck", "beast"],
["562", "swamp duck", "beast"],
["563", "rattlin' duck", "beast"],
["564", "vampire duck", "beast"],
["565", "zombie duck", "beast"],
["566", "drunk duck", "beast"],
["567", "mean drunk duck", "beast"],
["568", "boaraffe", "beast"],
["569", "The Clownlord Beelzebozo", "horror"],
["570", "rampaging adding machine", "construct"],
["571", "beefy bodyguard bat", "beast"],
["572", "Iiti Kitty", "undead"],
["573", "black cat", "beast"],
["574", "rolling stone", "elemental"],
["575", "tomb bat", "beast"],
["576", "Bailey's Beetle", "hippy"],
["577", "War Frat Mobile Grill Unit", "orc"],
["578", "usher", "dude"],
["579", "raven", "beast"],
["580", "bellhop", "dude"],
["581", "Ourang-Outang", "beast"],
["582", "Ancient Mariner", "dude"],
["583", "Kubla Khan", "dude"],
["584", "toothless mastiff bitch", "beast"],
["585", "angry poet", "dude"],
["586", "roller-skating Muse", "dude"],
["587", "can-can dancer", "dude"],
["588", "master of ceremonies", "dude"],
["589", "courtesan", "dude"],
["590", "voyeuristic artist", "dude"],
["591", "sensitive poet-type", "dude"],
["592", "X-dimensional horror", "horror"],
["593", "swamp beaver warrior", "beast"],
["594", "swamp beaver shaman", "beast"],
["595", "swamp gator", "beast"],
["596", "swamp entity", "elemental"],
["597", "conservationist hippy", "hippy"],
["598", "Mob Penguin Supervisor", "penguin"],
["599", "Mob Penguin Smith", "penguin"],
["600", "Mob Penguin Smasher", "penguin"],
["601", "concert pianist", "dude"],
["602", "best-selling novelist", "dude"],
["603", "malevolent crop circle", "construct"],
["604", "Bronze Chef", "construct"],
["605", "El Diablo", "construct"],
["606", "giant fried egg", "slime"],
["607", "possessed pipe-organ", "construct"],
["608", "Darkness (The Sorceress' Tower)", "elemental"],
["609", "endangered inflatable white tiger", "beast"],
["610", "fancy bath slug", "bug"],
["611", "collapsed mineshaft golem", "construct"],
["612", "giant bee", "bug"],
["613", "groovy pirate", "pirate"],
["614", "gritty pirate", "pirate"],
["615", "grassy pirate", "pirate"],
["616", "grungy pirate", "pirate"],
["617", "Knott Slanding", "beast"],
["618", "tipsy pirate", "pirate"],
["619", "tetchy pirate", "pirate"],
["620", "toothy pirate", "pirate"],
["621", "cleanly pirate", "pirate"],
["622", "creamy pirate", "pirate"],
["623", "curmudgeonly pirate", "pirate"],
["624", "chatty pirate", "pirate"],
["625", "crusty pirate", "pirate"],
["626", "clingy pirate (female)", "pirate"],
["627", "clingy pirate (male)", "pirate"],
["628", "whiny pirate", "pirate"],
["629", "witty pirate", "pirate"],
["630", "wacky pirate", "pirate"],
["631", "wealthy pirate", "pirate"],
["632", "warty pirate", "pirate"],
["633", "gaudy pirate", "pirate"],
["634", "booty crab", "beast"],
["635", "Novia Cad&aacute;ver", "undead"],
["636", "Novio Cad&aacute;ver", "undead"],
["637", "Padre Cad&aacute;ver", "undead"],
["638", "Persona Inocente Cad&aacute;ver", "undead"],
["639", "death ray in a pear tree", "construct"],
["640", "turtle mech", "construct"],
["641", "Swiss hen", "construct"],
["642", "killing bird", "construct"],
["643", "golden ring", "construct"],
["644", "goose a-laying", "construct"],
["645", "swarm a-swarming", "construct"],
["646", "blade a-spinning", "construct"],
["647", "laser lancing", "construct"],
["648", "borg a-beeping", "construct"],
["649", "strangler strangling", "construct"],
["650", "stomper stomping", "construct"],
["651", "Normal hobo", "hobo"],
["652", "infernal seal larva", "demon"],
["653", "infernal seal spawn", "demon"],
["654", "vengeful turtle spectre", "undead"],
["655", "haunted soup tureen", "undead"],
["656", "evil spaghetti cultist", "dude"],
["657", "evil spaghetti cult priest", "dude"],
["658", "slithering hollandaise glob", "slime"],
["659", "pernicious puddle of pesto", "slime"],
["660", "talking head", "weird"],
["661", "psychedelic fur", "weird"],
["662", "evil vihuela-playing mariachi", "dude"],
["663", "evil trumpet-playing mariachi", "dude"],
["664", "menacing construct", "construct"],
["665", "bizarre construct", "construct"],
["666", "industrious construct", "construct"],
["667", "towering construct", "construct"],
["668", "lonely construct", "construct"],
["669", "hulking construct", "construct"],
["670", "menacing construct", "construct"],
["671", "bizarre construct", "construct"],
["672", "industrious construct", "construct"],
["673", "towering construct", "construct"],
["674", "lonely construct", "construct"],
["675", "hulking construct", "construct"],
["679", "sewer gator", "beast"],
["680", "menacing thug", "dude"],
["681", "giant zombie goldfish", "undead"],
["682", "C. H. U. M.", "humanoid"],
["683", "Mob Penguin hitman", "penguin"],
["684", "hunting seal", "demon"],
["685", "turtle trapper", "dude"],
["686", "evil spaghetti cult assassin", "dude"],
["687", "b&eacute;arnaise zombie", "slime"],
["688", "Hodgman, The Hoboverlord", "hobo"],
["689", "Hot hobo", "hobo"],
["690", "Cold hobo", "hobo"],
["691", "Stench hobo", "hobo"],
["692", "Spooky hobo", "hobo"],
["693", "Sleaze hobo", "hobo"],
["694", "Ol' Scratch", "demon"],
["695", "Frosty", "elemental"],
["696", "Oscus", "hobo"],
["697", "Zombo", "undead"],
["698", "Chester", "dude"],
["699", "flock of seagulls", "beast"],
["700", "mariachi bandolero", "dude"],
["701", "Argarggagarg the Dire Hellseal", "demon"],
["702", "Safari Jack, Small-Game Hunter", "dude"],
["703", "Yakisoba the Executioner", "dude"],
["704", "Heimandatz, Nacho Golem", "construct"],
["705", "Jocko Homo", "beast"],
["706", "The Mariachi With No Name", "dude"],
["707", "gang of hobo muggers", "hobo"],
["708", "weather underground dweller", "humanoid"],
["709", "digital underground dweller", "humanoid"],
["710", "velvet underground dweller", "humanoid"],
["711", "spelunking astronaut", "dude"],
["712", "dwarvish gnome", "humanoid"],
["713", "possessed wine rack", "construct"],
["714", "skeletal sommelier", "undead"],
["715", "C. H. U. M. chieftain", "humanoid"],
["716", "amateur ninja", "dude"],
["717", "school of wizardfish", "fish"],
["718", "pumped-up bass", "fish"],
["719", "funk sole brother", "fish"],
["720", "migratory pirate", "pirate"],
["721", "ambulatory pirate", "pirate"],
["722", "peripatetic pirate", "pirate"],
["723", "scimitarfish", "fish"],
["724", "bazookafish", "fish"],
["725", "clubfish", "fish"],
["726", "mutant rattlesnake", "beast"],
["727", "mutant saguaro", "plant"],
["728", "mutant gila monster", "beast"],
["729", "swarm of mutant fire ants", "bug"],
["730", "roller skate", "fish"],
["731", "ice skate", "fish"],
["732", "Skate Board member", "fish"],
["733", "urchin urchin", "fish"],
["734", "grouper groupie", "fish"],
["735", "decent white shark", "fish"],
["736", "acoustic electric eel", "fish"],
["737", "ganger", "fish"],
["738", "octopus gardener", "fish"],
["739", "sponge", "fish"],
["740", "Neptune flytrap", "plant"],
["741", "stranglin' algae", "plant"],
["742", "Mer-kin scavenger", "mer-kin"],
["743", "cargo crab", "fish"],
["744", "drowned sailor", "undead"],
["745", "unholy diver", "horror"],
["746", "mine crab", "fish"],
["747", "mutant gift-wrapping elf", "elf"],
["748", "mutant doll-dressing elf", "elf"],
["749", "mutant cookie-baking elf", "elf"],
["750", "mutant whistle-carving elf", "elf"],
["751", "mutant circuit-soldering elf", "elf"],
["752", "Mob Penguin enforcer", "penguin"],
["753", "Mob Penguin goon", "penguin"],
["754", "Mob Penguin racketeer", "penguin"],
["755", "Mob Penguin hitpenguin", "penguin"],
["756", "Mob Penguin psychopath", "penguin"],
["757", "pufferfish", "fish"],
["758", "magic dragonfish", "fish"],
["759", "jamfish", "fish"],
["761", "Mer-kin diver", "mer-kin"],
["762", "diving belle", "undead"],
["763", "giant squid", "fish"],
["764", "fisherfish", "fish"],
["765", "Mer-kin miner", "mer-kin"],
["766", "Anemone combatant", "fish"],
["767", "killer clownfish", "horror"],
["768", "Mer-kin tippler", "mer-kin"],
["769", "nurse shark", "fish"],
["770", "lounge lizardfish", "fish"],
["771", "Mer-kin raider", "mer-kin"],
["772", "Mer-kin burglar", "mer-kin"],
["773", "Mer-kin healer", "mer-kin"],
["774", "trophyfish", "fish"],
["775", "sea cow", "fish"],
["776", "sea cowboy", "fish"],
["777", "Mer-kin rustler", "mer-kin"],
["778", "wild seahorse", "fish"],
["779", "hellseal pup", "demon"],
["780", "mother hellseal", "demon"],
["781", "hellseal guardian", "demon"],
["782", "guard turtle", "beast"],
["783", "guard turtle (french)", "beast"],
["791", "Slime", "slime"],
["792", "Mother Slime", "slime"],
["793", "Spawn of Wally", "horror"],
["794", "broodling seal", "demon"],
["795", "Centurion of Sparky", "horror"],
["796", "hermetic seal", "demon"],
["797", "watertight seal", "demon"],
["798", "shadow of Black Bubbles", "horror"],
["799", "Servant of Grodstank", "horror"],
["800", "heat seal", "demon"],
["801", "navy seal", "demon"],
["802", "wet seal", "demon"],
["803", "booth slime", "slime"],
["804", "fan slime", "slime"],
["805", "vendor slime", "slime"],
["806", "evil spaghetti cult middle-manager", "dude"],
["807", "evil spaghetti cult neophyte", "dude"],
["808", "evil spaghetti cult technician", "dude"],
["809", "hustled spectre", "undead"],
["810", "rotten dolphin thief", "fish"],
["811", "Cyrus the Virus", "bug"],
["812", "violent fungus", "plant"],
["813", "hostile amoeba", "slime"],
["814", "cluster of angry bacteria", "bug"],
["815", "mad flagellate", "bug"],
["816", "corrosive algae", "plant"],
["817", "giant octopus", "fish"],
["818", "giant bird-creature", "beast"],
["819", "giant jungle python", "beast"],
["820", "giant spider", "bug"],
["821", "wumpus", "beast"],
["822", "Bangyomaman Warrior", "dude"],
["823", "Handyman Jay Android", "construct"],
["824", "liquid metal robot", "construct"],
["825", "7-Foot Dwarf Replicant", "construct"],
["826", "Space Marine", "dude"],
["827", "ancient temple guardian", "construct"],
["828", "group of cultists", "dude"],
["829", "high priest of Ki'rhuss", "dude"],
["830", "ancient guardian statue", "construct"],
["831", "tribal goblin", "goblin"],
["832", "jungle baboon", "beast"],
["833", "evil cultist", "dude"],
["834", "cyborg policeman", "construct"],
["835", "obese tourist", "dude"],
["836", "terrifying robot", "construct"],
["838", "Mer-kin teacher", "mer-kin"],
["839", "Mer-kin punisher", "mer-kin"],
["840", "Mer-kin researcher", "mer-kin"],
["841", "Mer-kin trainer", "mer-kin"],
["842", "Mer-kin balldodger", "mer-kin"],
["843", "Mer-kin netdragger", "mer-kin"],
["844", "Mer-kin bladeswitcher", "mer-kin"],
["846", "rock homunculus", "beast"],
["847", "clod hopper", "beast"],
["848", "rockfish", "fish"],
["849", "Mer-kin poseur", "mer-kin"],
["850", "Mer-kin alphabetizer", "mer-kin"],
["851", "Mer-kin drifter", "mer-kin"],
["852", "Mer-kin monitor", "mer-kin"],
["853", "Mer-kin juicer", "mer-kin"],
["855", "breakdancing raver", "dude"],
["856", "pop-and-lock raver", "dude"],
["857", "running man", "dude"],
["858", "sleepy mariachi", "dude"],
["859", "surprised mariachi", "dude"],
["860", "alert mariachi", "dude"],
["861", "toilet-papered tree", "plant"],
["862", "fur tree", "plant"],
["863", "pumpkin tree", "plant"],
["864", "deadwood tree", "plant"],
["865", "hangman's tree", "plant"],
["866", "Underworld Tree", "plant"],
["867", "warehouse worker", "dude"],
["868", "evil spaghetti cult zealot", "dude"],
["869", "security slime", "slime"],
["870", "daft punk", "dude"],
["871", "mariachi bruiser", "dude"],
["872", "Gorgolok, the Infernal Seal (The Nemesis' Lair)", "demon"],
["873", "Stella, the Turtle Poacher (The Nemesis' Lair)", "dude"],
["874", "Spaghetti Elemental (The Nemesis' Lair)", "elemental"],
["875", "Lumpy, the Sinister Sauceblob (The Nemesis' Lair)", "slime"],
["876", "Spirit of New Wave (The Nemesis' Lair)", "undead"],
["877", "Somerset Lopez, Dread Mariachi (The Nemesis' Lair)", "dude"],
["879", "Georgepaul, the Balldodger", "mer-kin"],
["880", "Johnringo, the Netdragger", "mer-kin"],
["881", "Ringogeorge, the Bladeswitcher", "mer-kin"],
["882", "Gorgolok, the Infernal Seal (Volcanic Cave)", "demon"],
["883", "Stella, the Turtle Poacher (Volcanic Cave)", "dude"],
["884", "Spaghetti Elemental (Volcanic Cave)", "elemental"],
["885", "Lumpy, the Sinister Sauceblob (Volcanic Cave)", "slime"],
["886", "Spirit of New Wave (Volcanic Cave)", "undead"],
["887", "Somerset Lopez, Dread Mariachi (Volcanic Cave)", "dude"],
["888", "Gorgolok, the Demonic Hellseal", "demon"],
["889", "Stella, the Demonic Turtle Poacher", "demon"],
["890", "Spaghetti Demon", "demon"],
["891", "Lumpy, the Demonic Sauceblob", "demon"],
["892", "Demon of New Wave", "demon"],
["893", "Somerset Lopez, Demon Mariachi", "demon"],
["894", "monkey wrenchin' elf", "elf"],
["895", "saboteur elf", "elf"],
["896", "provocateur elf", "elf"],
["897", "raconteur elf", "elf"],
["898", "auteur elf", "elf"],
["899", "amateur elf", "elf"],
["900", "bolt-cuttin' elf", "elf"],
["901", "propaganda-spewin' elf", "elf"],
["902", "wire-crossin' elf", "elf"],
["903", "Edwing Abbidriel", "elf"],
["904", "Mob Penguin Kneecapper", "penguin"],
["905", "Mob Penguin Arsonist", "penguin"],
["906", "Mob Penguin Goon", "penguin"],
["907", "Mob Penguin Caporegime", "penguin"],
["908", "Mob Penguin Demolitionist", "penguin"],
["909", "Mesmerizing Penguin", "penguin"],
["910", "Undercover Penguin", "penguin"],
["911", "Black-and-White-Ops Penguin", "penguin"],
["912", "Cement Cobbler Penguin", "penguin"],
["914", "menacing lawn gnome", "humanoid"],
["915", "mowing lawn gnome", "humanoid"],
["916", "mounted lawn gnome", "humanoid"],
["917", "The Landscaper", "demon"],
["918", "BRICKO ooze", "construct"],
["919", "BRICKO bat", "construct"],
["920", "BRICKO oyster", "construct"],
["921", "BRICKO turtle", "construct"],
["922", "BRICKO elephant", "construct"],
["923", "BRICKO octopus", "construct"],
["924", "BRICKO python", "construct"],
["925", "BRICKO vacuum cleaner", "construct"],
["926", "BRICKO airship", "construct"],
["927", "BRICKO cathedral", "construct"],
["928", "BRICKO gargantuchicken", "construct"],
["929", "croqueteer", "dude"],
["930", "Tiger-lily", "plant"],
["931", "wasp in a wig", "bug"],
["932", "beelephant", "beast"],
["933", "snapdragon", "plant"],
["934", "lowercase B", "slime"],
["935", "swarm of lowercase As", "bug"],
["936", "lowercase H", "horror"],
["937", "uppercase Q", "dude"],
["938", "lowercase K", "humanoid"],
["939", "Professor Jacking", "dude"],
["940", "cruel dust mote", "weird"],
["941", "malevolent magnetic field", "weird"],
["942", "funk particle", "weird"],
["943", "Castle in the Clouds in the Sky", "construct"],
["944", "Spookyraven Manor (monster)", "construct"],
["945", "loose coalition of yetis, snowmen, and goats", "beast"],
["946", "Fearsome Wacken", "beast"],
["947", "jungle scabie", "bug"],
["948", "smooth jazz scabie", "bug"],
["949", "The Whole Kingdom", "construct"],
["950", "ghost", "undead"],
["951", "fleaman", "dude"],
["952", "medusa", "horror"],
["953", "Vanya's Creature", "construct"],
["954", "orcish juvenile delinquent", "orc"],
["955", "orcish frat wannaboy", "orc"],
["956", "actual orcish frat boy", "orc"],
["957", "jailbait orquette", "orc"],
["958", "juvenile delinquent orquette", "orc"],
["959", "totally trashed orquette", "orc"],
["960", "Timmy Tofurkey cast member", "dude"],
["961", "Susie Soyburger cast member", "dude"],
["962", "Neptune, the Dog that Is a Respected Equal and Not a Pet cast member", "beast"],
["963", "Timmy Tofurkey", "humanoid"],
["964", "Susie Soyburger", "humanoid"],
["965", "Neptune, the Dog that Is a Respected Equal and Not a Pet", "beast"],
["966", "Essence of Tofu", "elemental"],
["967", "Essence of Soy", "elemental"],
["968", "Essence of Interspecies Respect", "elemental"],
["969", "angry bassist", "dude"],
["970", "evil ex-girlfriend", "dude"],
["971", "peeved roommate", "dude"],
["972", "blue-haired girl", "dude"],
["973", "random scenester", "dude"],
["974", "deadly venomtrout", "fish"],
["975", "water spider", "bug"],
["976", "unearthed monstrosity", "horror"],
["977", "suckubus", "demon"],
["978", "inkubus", "demon"],
["979", "Pr Imp", "demon"],
["980", "BL Imp", "demon"],
["981", "CH Imp", "demon"],
["982", "serialbus", "demon"],
["983", "Victor the Insult Comic Hellhound", "demon"],
["984", "Larry of the Field of Signs", "demon"],
["985", "Carbuncle Top", "demon"],
["986", "reanimated bat skeleton", "undead"],
["987", "reanimated serpent skeleton", "undead"],
["988", "reanimated baboon skeleton", "undead"],
["989", "reanimated wyrm skeleton", "undead"],
["990", "reanimated demon skeleton", "undead"],
["991", "reanimated giant spider skeleton", "undead"],
["992", "crate", "construct"],
["993", "werecougar", "dude"],
["994", "plastered frat orc", "orc"],
["995", "bunch of drunken rats", "beast"],
["996", "drunken rat king", "beast"],
["997", "tomb rat king", "beast"],
["998", "drunken 7-foot dwarf", "humanoid"],
["999", "skeleton with a mop", "undead"],
["1000", "unemployed knob goblin", "goblin"],
["1001", "skeleton invader", "undead"],
["1002", "two skeleton invaders", "undead"],
["1003", "three skeleton invaders", "undead"],
["1004", "four skeleton invaders", "undead"],
["1005", "five skeleton invaders", "undead"],
["1006", "ten skeletons", "undead"],
["1010", "screambat", "beast"],
["1031", "Hobelf (Elf Alley)", "hobo"],
["1048", "your butt", "dude"],
["1049", "somebody else's butt", "dude"],
["1050", "Hobelf (WC)", "hobo"],
["1057", "Knob Goblin Elite Guard", "goblin"],
["1058", "off-duty Knob Goblin Elite Guard", "goblin"],
["1059", "swarm of Knob lice", "bug"],
["1060", "Cobb's Knob oven", "construct"],
["1061", "Knob Goblin Harem Guard", "goblin"],
["1062", "Knob Goblin Madam", "goblin"],
["1063", "Knob Goblin Accountant", "goblin"],
["1064", "Knob Goblin MBA", "goblin"],
["1065", "Knob Goblin Alchemist", "goblin"],
["1070", "modern zmobie", "undead"],
["1071", "dirty old lihc", "undead"],
["1072", "swarm of ghuol whelps", "undead"],
["1073", "big swarm of ghuol whelps", "undead"],
["1074", "giant swarm of ghuol whelps", "undead"],
["1075", "mumblebee", "bug"],
["1076", "moneybee", "bug"],
["1077", "beebee gunners", "bug"],
["1078", "buzzerker", "bug"],
["1079", "bee swarm", "bug"],
["1080", "beebee queue", "bug"],
["1081", "bee thoven", "bug"],
["1082", "Beebee King", "bug"],
["1083", "Queen Bee", "bug"],
["1084", "unhinged survivor", "dude"],
["1085", "grizzled survivor", "dude"],
["1086", "whiny survivor", "dude"],
["1087", "unlikely survivor", "dude"],
["1088", "overarmed survivor", "dude"],
["1089", "primitive survivor", "dude"],
["1090", "cat-alien", "horror"],
["1091", "dog-alien", "horror"],
["1092", "alielf", "horror"],
["1093", "dogcat", "horror"],
["1094", "hamsterpus", "horror"],
["1095", "ferrelf", "horror"],
["1096", "alien hamsterpus", "horror"],
["1097", "mutated alielf", "horror"],
["1098", "mutated alielephant", "horror"],
["1099", "antique database server", "construct"],
["1100", "Wu Tang the Betrayer", "dude"],
["1101", "family of kobolds", "humanoid"],
["1102", "sexy sorority ghost", "undead"],
["1103", "sexy sorority skeleton", "undead"],
["1104", "sexy sorority vampire", "undead"],
["1105", "sexy sorority zombie", "undead"],
["1106", "sexy sorority werewolf", "dude"],
["1110", "tumbleweed", "plant"],
["1111", "lollipede", "bug"],
["1112", "lollicat", "beast"],
["1113", "lolligator", "beast"],
["1114", "lolliphaunt", "beast"],
["1115", "lolrus", "beast"],
["1116", "fudge weasel", "beast"],
["1117", "fudge monkey", "beast"],
["1118", "fudge vulture", "beast"],
["1119", "fudge oyster", "beast"],
["1120", "fudge poodle", "beast"],
["1122", "Whimpering Willow", "plant"],
["1123", "Suffering Juniper", "plant"],
["1124", "Tormented Baobab", "plant"],
["1125", "Sorrowful Hickory", "plant"],
["1126", "Woeful Magnolia", "plant"],
["1127", "The Thorax", "beast"],
["1128", "The Bat in the Spats", "beast"],
["1129", "Mortimer Strauss", "undead"],
["1130", "Bettie Barulio", "undead"],
["1131", "Marvin J. Sunny", "undead"],
["1132", "Wonderful Winifred Wongle", "undead"],
["1133", "Marcus Macurgeon", "undead"],
["1134", "The Terrible Pinch", "humanoid"],
["1135", "Thug 1 and Thug 2", "humanoid"],
["1136", "Hugo Von Douchington", "dude"],
["1137", "Wacky Zack Flacky", "dude"],
["1138", "Dolores D. Smiley", "dude"],
["1139", "Vivian Vibrian Vumian Varr", "dude"],
["1140", "Brock \"Rocky\" Flox", "dude"],
["1141", "The Large-Bellied Snitch", "beast"],
["1142", "Mammon the Elephant", "beast"],
["1143", "The Thing with No Name", "humanoid"],
["1144", "swarm of fudgewasps", "bug"],
["1149", "sleepy 7-Foot Dwarf", "humanoid"],
["1150", "dopey 7-Foot Dwarf", "humanoid"],
["1151", "grumpy 7-Foot Dwarf", "humanoid"],
["1152", "The Luter", "undead"],
["1153", "mountain man", "construct"],
["1154", "eXtreme cross-country hippy", "hippy"],
["1155", "eXtreme Orcish snowboarder", "orc"],
["1156", "sk8 gnome", "humanoid"],
["1157", "Groar", "beast"],
["1158", "The Avatar of Sneaky Pete", "dude"],
["1159", "stone temple pirate", "construct"],
["1160", "baa-relief sheep", "construct"],
["1161", "craven carven raven", "construct"],
["1162", "clan of cave bars", "beast"],
["1163", "Baa'baa'bu'ran", "construct"],
["1164", "four-shadowed mime", "horror"],
["1165", "scavenger bugbear", "beast"],
["1166", "hypodermic bugbear", "beast"],
["1167", "batbugbear", "beast"],
["1168", "bugbear scientist", "beast"],
["1169", "bugaboo", "undead"],
["1170", "Black Ops Bugbear", "beast"],
["1171", "Battlesuit Bugbear Type", "beast"],
["1172", "ancient unspeakable bugbear", "beast"],
["1173", "trendy bugbear chef", "beast"],
["1174", "creepy eye-stalk tentacle monster", "horror"],
["1175", "grouchy furry monster", "beast"],
["1176", "anesthesiologist bugbear", "beast"],
["1177", "bugbear robo-surgeon", "construct"],
["1178", "spiderbugbear", "beast"],
["1179", "bugbear mortician", "beast"],
["1180", "bugbear drone", "construct"],
["1181", "liquid metal bugbear", "construct"],
["1182", "Bugbear Captain", "beast"],
["1183", "angry cavebugbear", "beast"],
["1184", "N-space Virtual Assistant", "construct"],
["1185", "ninja snowman assassin", "elemental"],
["1186", "Black Crayon Man", "dude"],
["1187", "Black Crayon Beast", "beast"],
["1188", "Black Crayon Golem", "construct"],
["1189", "Black Crayon Undead Thing", "undead"],
["1190", "Black Crayon Manloid", "humanoid"],
["1191", "Black Crayon Beetle", "bug"],
["1192", "Black Crayon Hippy", "hippy"],
["1193", "Black Crayon Frat Orc", "orc"],
["1194", "Black Crayon Demon", "demon"],
["1195", "Black Crayon Shambling Monstrosity", "horror"],
["1196", "Black Crayon Fish", "fish"],
["1197", "Black Crayon Goblin", "goblin"],
["1198", "Black Crayon Pirate", "pirate"],
["1199", "Black Crayon Flower", "plant"],
["1200", "Black Crayon Spiraling Shape", "weird"],
["1201", "Black Crayon Crimbo Elf", "elf"],
["1202", "Black Crayon Mer-kin", "mer-kin"],
["1203", "Black Crayon Slime", "slime"],
["1204", "Black Crayon Penguin", "penguin"],
["1205", "Black Crayon Elemental", "elemental"],
["1206", "Black Crayon Constellation", "constellation"],
["1207", "Black Crayon Hobo", "hobo"],
["1209", "snakefire in the grassfire", "beast"],
["1210", "blazing bat", "beast"],
["1211", "Servant of Lord Flameface (monster)", "demon"],
["1213", "zombie-huntin' feller", "dude"],
["1214", "Norville Rogers", "dude"],
["1215", "Peacannon", "plant"],
["1216", "Scott the Miner", "dude"],
["1217", "Father McGruber", "dude"],
["1218", "Herman East, Relivinator", "dude"],
["1219", "Angry Space Marine", "dude"],
["1220", "Deputy Nick Soames & Earl", "dude"],
["1221", "Father Nikolai Ravonovich", "dude"],
["1222", "Charity the Zombie Hunter", "dude"],
["1223", "Special Agent Wallace Burke Corrigan", "dude"],
["1224", "Hank North, Photojournalist", "dude"],
["1225", "rag-tag band of survivors", "dude"],
["1226", "Wesley J. \"Wes\" Campbell", "dude"],
["1227", "The Free Man", "dude"],
["1228", "panicking Knott Yeti", "beast"],
["1229", "Rene C. Corman (Zombie Slayer)", "dude"],
["1230", "smut orc jacker", "orc"],
["1231", "smut orc pipelayer", "orc"],
["1232", "smut orc nailer", "orc"],
["1233", "smut orc screwer", "orc"],
["1234", "smut orc pervert", "orc"],
["1235", "oil slick", "slime"],
["1236", "oil tycoon", "slime"],
["1237", "oil baron", "slime"],
["1238", "oil cartel", "slime"],
["1239", "skulldozer", "undead"],
["1240", "Bubblemint Twins", "dude"],
["1241", "Big Wheelin' Twins", "dude"],
["1242", "Mismatched Twins", "dude"],
["1243", "Creepy Ginger Twin", "dude"],
["1244", "Troll Twins", "dude"],
["1245", "spider (duck?) topiary animal", "beast"],
["1246", "bearpig topiary animal", "beast"],
["1247", "elephant (meatcar?) topiary animal", "beast"],
["1248", "little blob of gray goo", "horror"],
["1249", "largish blob of gray goo", "horror"],
["1250", "enormous blob of gray goo", "horror"],
["1251", "plastic-extruding animelf", "elf"],
["1252", "tiny-screwing animelf", "elf"],
["1253", "circuit-soldering animelf", "elf"],
["1254", "Claybender Sorcerer Ghost", "undead"],
["1255", "Dusken Raider Ghost", "undead"],
["1256", "Space Tourist Explorer Ghost", "undead"],
["1257", "Battlie Knight Ghost", "undead"],
["1258", "Whatsian Commando Ghost", "undead"],
["1259", "quality control animelf", "elf"],
["1260", "toy assembling animelf", "elf"],
["1261", "sign-twirling Crimbo elf", "elf"],
["1262", "taco-clad Crimbo elf", "elf"],
["1263", "tacobuilding elf", "elf"],
["1264", "Anger Man", "dude"],
["1265", "rage flame", "elemental"],
["1266", "ticking time bomb", "construct"],
["1267", "frustrating knight", "dude"],
["1268", "Fear Man", "dude"],
["1269", "morbid skull", "undead"],
["1270", "animated possessions", "construct"],
["1271", "natural spider", "bug"],
["1272", "Doubt Man", "dude"],
["1273", "work hat", "construct"],
["1274", "reproachful heart", "construct"],
["1275", "judgmental eye", "beast"],
["1276", "Regret Man", "dude"],
["1277", "contemplative ghost", "undead"],
["1278", "lovesick ghost", "undead"],
["1279", "ancient ghost", "undead"],
["1280", "spider conspirator", "bug"],
["1281", "goblin conspirator", "goblin"],
["1282", "tin can conspirator", "construct"],
["1283", "canned goblin conspirator", "construct"],
["1284", "tin spider conspirator", "construct"],
["1285", "spider-goblin conspirator", "horror"],
["1286", "Fnord the Unspeakable", "horror"],
["1287", "bacon snake", "beast"],
["1288", "pork butterfly", "bug"],
["1289", "groast", "undead"],
["1290", "salaminder", "beast"],
["1291", "cold cutter", "construct"],
["1292", "The Beefhemoth", "beast"],
["1293", "Whisk of Misery", "weird"],
["1294", "Butterknife of Regret", "weird"],
["1295", "Spatula of Despair", "weird"],
["1296", "Cookie Cutter of Loneliness", "weird"],
["1297", "Creme Brulee Torch of Fury", "weird"],
["1298", "carton of Eggs of Confidence", "weird"],
["1299", "loaf of Bread of Wonder", "weird"],
["1300", "bag of Potatoes of Security", "weird"],
["1301", "bundle of Meat of Happiness", "weird"],
["1302", "box of Batter Mix of Hope", "weird"],
["1303", "roasted duck golem", "construct"],
["1304", "lucky cat statue", "construct"],
["1305", "grinning pork bun", "construct"],
["1306", "triad code wizard", "dude"],
["1307", "clean-room daemon", "demon"],
["1308", "fabricator gu&agrave;i", "demon"],
["1309", "The Sierpinski brothers", "dude"],
["1310", "yakuza courier", "humanoid"],
["1311", "yakuza guard", "humanoid"],
["1312", "salaryninja", "dude"],
["1313", "security robot", "construct"],
["1314", "Chief Electronic Overseer", "construct"],
["1315", "desperate gold farmer", "dude"],
["1316", "rabid MMO addict", "dude"],
["1317", "yakuza thug", "humanoid"],
["1318", "The Server", "construct"],
["1319", "White Bone Demon", "demon"],
["1320", "fearsome giant squid", "fish"],
["1321", "giant man-eating shark", "fish"],
["1322", "ferocious roc", "beast"],
["1323", "procedurally-generated skeleton", "undead"],
["1324", "The Cray-Kin", "fish"],
["1325", "Bristled Man-O-War", "fish"],
["1326", "Deadly Hydra", "beast"],
["1327", "Video Game Minion (weak)", "construct"],
["1328", "Video Game Minion (moderate)", "construct"],
["1329", "Video Game Minion (strong)", "construct"],
["1330", "Video Game Miniboss", "construct"],
["1331", "Video Game Boss", "construct"],
["1332", "Fitness Giant", "humanoid"],
["1333", "Neckbeard Giant", "humanoid"],
["1334", "Foodie Giant", "humanoid"],
["1335", "Renaissance Giant", "humanoid"],
["1336", "Punk Rock Giant", "humanoid"],
["1337", "Steampunk Giant", "humanoid"],
["1338", "Clancy (monster)", "dude"],
["1339", "The Avatar of Boris", "dude"],
["1341", "huge mosquito", "bug"],
["1342", "mega frog", "beast"],
["1343", "smell-o-the-wisp", "elemental"],
["1344", "swamp hag", "dude"],
["1345", "bog leech", "bug"],
["1346", "bog skeleton", "undead"],
["1347", "haunted skullabra", "undead"],
["1348", "bogart", "humanoid"],
["1349", "swamp beaver lumberjack", "beast"],
["1350", "swamp owl", "beast"],
["1351", "mud turtle", "beast"],
["1352", "the ghost of Phil Bunion", "undead"],
["1353", "swamp skunk", "beast"],
["1354", "wastoid", "dude"],
["1355", "dweebie", "dude"],
["1356", "sporto", "dude"],
["1357", "motorhead", "dude"],
["1358", "out-of-control bandsaw", "construct"],
["1359", "deadly vise", "construct"],
["1360", "X-fingered Shop Teacher", "dude"],
["1361", "screw golem", "construct"],
["1362", "demonic jigsaw", "demon"],
["1363", "Bunsen burner and beaker", "construct"],
["1364", "dropped base", "slime"],
["1365", "sodium golem", "construct"],
["1366", "possessed eyewashing station", "demon"],
["1367", "rulergheist", "undead"],
["1368", "clay golem", "construct"],
["1369", "misproportioned portrait", "construct"],
["1370", "wire sculpture", "construct"],
["1371", "moister oyster", "fish"],
["1372", "Mer-kin specter", "undead"],
["1373", "eye in the darkness", "horror"],
["1374", "school of many", "horror"],
["1375", "slithering thing", "horror"],
["1376", "Peanut", "horror"],
["1377", "Shub-Jigguwatt, Elder God of Violence", "horror"],
["1378", "Yog-Urt, Elder Goddess of Hatred", "horror"],
["1379", "Dad Sea Monkee", "horror"],
["1386", "Falls-From-Sky", "beast"],
["1387", "Great Wolf of the Air", "beast"],
["1388", "Zombie Homeowners' Association", "undead"],
["1389", "Mayor Ghost", "undead"],
["1390", "Count Drunkula", "undead"],
["1391", "The Unkillable Skeleton", "undead"],
["1392", "hot bugbear", "beast"],
["1393", "cold bugbear", "beast"],
["1394", "spooky bugbear", "beast"],
["1395", "stench bugbear", "beast"],
["1396", "sleaze bugbear", "beast"],
["1397", "hot werewolf", "beast"],
["1398", "cold werewolf", "beast"],
["1399", "spooky werewolf", "beast"],
["1400", "stench werewolf", "beast"],
["1401", "sleaze werewolf", "beast"],
["1402", "hot zombie", "undead"],
["1403", "cold zombie", "undead"],
["1404", "spooky zombie", "undead"],
["1405", "stench zombie", "undead"],
["1406", "sleaze zombie", "undead"],
["1407", "hot ghost", "undead"],
["1408", "cold ghost", "undead"],
["1409", "spooky ghost", "undead"],
["1410", "stench ghost", "undead"],
["1411", "sleaze ghost", "undead"],
["1412", "hot vampire", "undead"],
["1413", "cold vampire", "undead"],
["1414", "spooky vampire (Dreadsylvanian Castle)", "undead"],
["1415", "stench vampire", "undead"],
["1416", "sleaze vampire", "undead"],
["1417", "hot skeleton", "undead"],
["1418", "cold skeleton", "undead"],
["1419", "spooky skeleton", "undead"],
["1420", "stench skeleton", "undead"],
["1421", "sleaze skeleton", "undead"],
["1422", "QuickBASIC elemental", "elemental"],
["1423", "Fran&ccedil;ois Verte, Art Teacher", "dude"],
["1424", "Mrs. K, the Chemistry Teacher", "dude"],
["1425", "Principal Mooney", "dude"],
["1426", "dense liana", "plant"],
["1427", "pygmy janitor", "dude"],
["1428", "pygmy shaman", "dude"],
["1429", "pygmy witch surgeon", "dude"],
["1430", "pygmy witch accountant", "dude"],
["1431", "drunk pygmy", "dude"],
["1432", "pygmy bowler", "dude"],
["1433", "pygmy witch nurse", "dude"],
["1434", "pygmy witch lawyer", "dude"],
["1435", "pygmy orderlies", "dude"],
["1436", "junksprite sharpener", "humanoid"],
["1437", "junksprite bender", "humanoid"],
["1438", "junksprite melter", "humanoid"],
["1439", "Doctor Oh, the Junksprite Boss", "humanoid"],
["1440", "scout seal", "demon"],
["1441", "bulwark bull seal", "demon"],
["1442", "official seal", "demon"],
["1443", "Infernal Officer", "demon"],
["1444", "stiff disco dancer", "construct"],
["1445", "awkward disco dancer", "dude"],
["1446", "flexible disco dancer", "dude"],
["1447", "The Sagittarian", "dude"],
["1448", "vandal kid", "dude"],
["1449", "kid who is too old to be Trick-or-Treating", "dude"],
["1450", "suburban security civilian", "dude"],
["1451", "All-Hallow's Steve", "dude"],
["1452", "depressing French accordionist", "dude"],
["1453", "lively Cajun accordionist", "dude"],
["1454", "quirky indie-rock accordionist", "dude"],
["1455", "Frank &quot;Skipper&quot; Dan, the Accordion Lord", "dude"],
["1456", "spirit bedbug", "undead"],
["1457", "spirit pea", "undead"],
["1458", "spirit faucet", "undead"],
["1459", "Warbear Foot Soldier", "beast"],
["1460", "spirit alarm clock", "undead"],
["1461", "Possessed Can of Linguine-Os", "weird"],
["1462", "Frozen Bag of Tortellini", "weird"],
["1463", "Possessed Jar of Alphredo&trade;", "weird"],
["1464", "Box of Crafty Dinner", "weird"],
["1465", "Possessed Can of Creepy Pasta", "weird"],
["1466", "Chef Boy, R&amp;D", "dude"],
["1467", "Warbear Officer", "beast"],
["1468", "High-Ranking Warbear Officer", "beast"],
["1470", "steaming straw house", "construct"],
["1471", "frosty straw house", "construct"],
["1472", "Dutch Angle straw house", "construct"],
["1473", "befouled straw house", "construct"],
["1474", "oily straw house", "construct"],
["1475", "glowing ash house", "construct"],
["1476", "cold ironwood house", "construct"],
["1477", "quaking aspen house", "construct"],
["1478", "pitch pine house", "construct"],
["1479", "slippery elm house", "construct"],
["1480", "brick kiln", "construct"],
["1481", "brick icehouse", "construct"],
["1482", "brick mausoleum", "construct"],
["1483", "brick outhouse", "construct"],
["1484", "brick (suggestive pause) house", "construct"],
["1485", "treadmill", "construct"],
["1486", "rack of free weights", "construct"],
["1487", "Abcrusher 4000&trade;", "construct"],
["1488", "Escalatormaster&trade;", "construct"],
["1489", "Legstrong&trade; stationary bicycle", "construct"],
["1490", "school of gummi piranhas", "fish"],
["1491", "gummi plesiosaur", "beast"],
["1492", "lemonhead minnow", "fish"],
["1493", "Rock Pop weasel", "beast"],
["1494", "chocolate hare", "beast"],
["1495", "chocolate-cherry prairie dog", "beast"],
["1496", "candied pecan tree", "plant"],
["1497", "licorice snake", "beast"],
["1498", "tricksy pixie", "humanoid"],
["1499", "fire truck", "construct"],
["1500", "ice cream truck", "construct"],
["1501", "sewer tanker", "construct"],
["1502", "monster hearse", "construct"],
["1503", "sketchy van", "construct"],
["1504", "Medieval strawman debator", "dude"],
["1505", "Medieval leather mug salesman", "dude"],
["1506", "Medieval potter", "dude"],
["1507", "Medieval dung peddler", "dude"],
["1508", "Medieval stucco artisan", "dude"],
["1509", "Medieval mug apprentice", "dude"],
["1510", "Copperhead Club bartender", "dude"],
["1511", "Mob Penguin Capo", "penguin"],
["1512", "ninja dressed as a waiter", "dude"],
["1513", "waiter dressed as a ninja", "dude"],
["1514", "Frozen Solid Snake", "beast"],
["1515", "The Frattlesnake", "beast"],
["1516", "The Snake With Like Ten Heads", "beast"],
["1517", "Batsnake", "beast"],
["1518", "Burning Snake of Fire", "beast"],
["1519", "Snakeleton", "beast"],
["1520", "man with the red buttons", "dude"],
["1521", "red skeleton", "undead"],
["1522", "red butler", "dude"],
["1523", "Red Herring", "dude"],
["1524", "Red Snapper", "dude"],
["1525", "Red Fox", "dude"],
["1526", "lynyrd skinner", "dude"],
["1527", "fleet woodsman", "dude"],
["1528", "Blue Oyster cultist", "dude"],
["1529", "eagle", "beast"],
["1530", "Jefferson pilot", "dude"],
["1531", "Ron \"The Weasel\" Copperhead", "dude"],
["1532", "fan dancer", "dude"],
["1533", "lynyrd", "beast"],
["1534", "The Nuge", "dude"],
["1535", "The Avatar of Jarlsberg", "dude"],
["1536", "Thinknerd Sorting Robot", "construct"],
["1537", "Thinknerd Moving Robot", "construct"],
["1538", "Thinknerd Packing Robot", "construct"],
["1539", "amok putty", "slime"],
["1540", "Wardr&ouml;b nightstand", "construct"],
["1541", "animated mahogany nightstand", "construct"],
["1542", "animated ornate nightstand", "construct"],
["1543", "animated rustic nightstand", "construct"],
["1544", "elegant animated nightstand", "construct"],
["1545", "cosmetics wraith", "undead"],
["1546", "Jacob's adder", "beast"],
["1547", "model skeleton", "construct"],
["1548", "the gunk", "slime"],
["1549", "creepy doll", "construct"],
["1550", "possessed toy chest", "weird"],
["1551", "spooky music box", "construct"],
["1552", "stuffed moose head", "beast"],
["1553", "full-length mirror", "construct"],
["1554", "ancestral Spookyraven portrait", "construct"],
["1555", "sheet ghost", "undead"],
["1556", "monstrous boiler", "construct"],
["1557", "steam elemental", "elemental"],
["1558", "coaltergeist", "undead"],
["1559", "Bram the Stoker", "undead"],
["1560", "plaid ghost", "undead"],
["1561", "cabinet of Dr. Limpieza", "undead"],
["1562", "possessed laundry press", "construct"],
["1563", "mad wino", "hobo"],
["1564", "ghost of Elizabeth Spookyraven", "undead"],
["1565", "Stephen Spookyraven", "undead"],
["1566", "Sloppy Seconds Burger", "weird"],
["1567", "Sloppy Seconds Cocktail", "weird"],
["1568", "Sloppy Seconds Sundae", "weird"],
["1569", "Fun-Guy Playmate", "plant"],
["1570", "wild girl", "dude"],
["1571", "broctopus", "fish"],
["1572", "cocktail shrimp", "fish"],
["1573", "taco fish", "fish"],
["1574", "son of a son of a sailor", "dude"],
["1575", "drownedbeat", "dude"],
["1576", "black magic woman", "dude"],
["1577", "black friar", "dude"],
["1578", "pair of burnouts", "dude"],
["1579", "biclops", "humanoid"],
["1580", "spider-legged witch's hut", "construct"],
["1581", "extremely annoyed witch", "dude"],
["1582", "Elp&iacute;zo & Crosybdis", "beast"],
["1583", "sticky mummy", "undead"],
["1584", "giant mob of baby spiders", "bug"],
["1585", "Government agent", "dude"],
["1586", "perimeter defense sphere", "construct"],
["1587", "illegal alien", "humanoid"],
["1588", "space beast", "beast"],
["1589", "space beast matriarch", "beast"],
["1590", "white elephant", "beast"],
["1591", "pig", "beast"],
["1592", "pterodactyl", "beast"],
["1593", "sabre-toothed kiwi", "beast"],
["1594", "droll", "humanoid"],
["1595", "Adventurer echo", "dude"],
["1596", "surprised and annoyed witch", "dude"],
["1597", "giant isopod", "bug"],
["1598", "gourmet gourami", "fish"],
["1599", "freshwater bonefish", "fish"],
["1600", "alley catfish", "fish"],
["1601", "piranhadon", "fish"],
["1602", "storm cow", "beast"],
["1603", "aquaconda", "beast"],
["1604", "giant tardigrade", "bug"],
["1605", "Aquabat", "beast"],
["1606", "Aquagoblin", "goblin"],
["1607", "Auqadargon", "undead"],
["1608", "Dr. Aquard", "dude"],
["1609", "Lord Soggyraven", "undead"],
["1610", "Protector Spurt", "undead"],
["1611", "Gurgle", "beast"],
["1612", "Big Wisnaqua", "dude"],
["1613", "The Aquaman", "dude"],
["1614", "The Rain King", "dude"],
["1615", "Mob Penguin entrepreneur", "penguin"],
["1616", "hep cat", "dude"],
["1617", "cigarette girl", "dude"],
["1618", "Moonshriner", "dude"],
["1619", "unstill", "construct"],
["1620", "banjoccultist", "dude"],
["1621", "Caveman Dan", "dude"],
["1622", "giant rubber spider", "bug"],
["1623", "Gladiator", "dude"],
["1624", "Sadiator", "dude"],
["1625", "Madiator", "dude"],
["1626", "Radiator", "dude"],
["1627", "cheap strix", "beast"],
["1628", "hypocritical medicus", "dude"],
["1629", "holographic army", "weird"],
["1630", "Xiblaxian political prisoner", "weird"],
["1631", "They", "humanoid"],
["1632", "one of Doctor Weirdeaux's creations", "beast"],
["1633", "government scientist", "dude"],
["1634", "lab monkey", "beast"],
["1635", "creepy little girl", "dude"],
["1636", "super-sized Cola Wars soldier", "dude"],
["1637", "Venus mantrap", "plant"],
["1638", "bigface", "humanoid"],
["1639", "smoke monster", "weird"],
["1640", "Mercenary of Fortune", "dude"],
["1641", "T-9000", "construct"],
["1642", "damned dirty ape", "beast"],
["1643", "jet-ski bandit", "dude"],
["1644", "Z-Rex", "undead"],
["1645", "superdupervirus", "horror"],
["1646", "sentient ATM", "construct"],
["1647", "E.V.E., the robot zombie", "construct"],
["1648", "exo-suited miner", "elf"],
["1649", "semi-autonomous drill unit", "elf"],
["1650", "ambulatory robo-minecart", "elf"],
["1651", "oddly-proportioned ghost", "horror"],
["1652", "large-headed werewolf", "horror"],
["1653", "giant pumpkin-head", "horror"],
["1656", "gamblin' man", "dude"],
["1657", "animated spittoon", "construct"],
["1658", "outlaw behind an table", "dude"],
["1659", "craggy bartender", "dude"],
["1660", "tetched prospector", "dude"],
["1661", "cowskeleton", "undead"],
["1662", "nest of rattlers", "beast"],
["1663", "outlaw leader", "dude"],
["1664", "Boss Bat?", "undead"],
["1665", "new Knob Goblin King", "goblin"],
["1666", "Donerbagon", "undead"],
["1667", "winged yeti", "beast"],
["1668", "hulking bridge troll", "humanoid"],
["1669", "%playername the Adventurer", "dude"],
["1670", "Cheetahman", "dude"],
["1671", "Microwave Magus", "dude"],
["1672", "Kung-Fu Hustler (monster)", "dude"],
["1673", "Tasmanian Dervish", "dude"],
["1674", "Macho Man", "dude"],
["1675", "Iron Chef", "dude"],
["1676", "Entire Shoplifter", "dude"],
["1677", "Mr. Loathing", "dude"],
["1678", "Accountant-Barbarian", "dude"],
["1679", "Metaphysical Gastronomist", "dude"],
["1680", "Kleptobrainiac", "dude"],
["1681", "The Mastermind", "dude"],
["1682", "Savage Beatnik", "dude"],
["1683", "Creamweaver", "dude"],
["1684", "Smooth Criminal (monster)", "dude"],
["1685", "Seannery the Conman", "dude"],
["1686", "Fire Fighter", "dude"],
["1687", "Cereal Arsonist", "dude"],
["1688", "Burnglar", "dude"],
["1689", "The Lavalier", "dude"],
["1690", "Snowbrawler", "dude"],
["1691", "Ice Cream Conjurer", "dude"],
["1692", "Iceberglar", "dude"],
["1693", "Mrs. Freeze", "dude"],
["1694", "Granola Barbarian", "dude"],
["1695", "Cheese Wizard", "dude"],
["1696", "Assassin", "dude"],
["1697", "Odorous Humongous", "dude"],
["1698", "Ghostpuncher", "dude"],
["1699", "Plague Chef", "dude"],
["1700", "Batburglar", "dude"],
["1701", "Arthur Frankenstein", "dude"],
["1702", "Grease Trapper", "dude"],
["1703", "Ham Shaman", "dude"],
["1704", "Porkpocket", "dude"],
["1705", "Leonard", "dude"],
["1706", "wall of meat", "elemental"],
["1707", "wall of skin", "construct"],
["1708", "wall of bones", "undead"],
["1710", "topiary gopher", "plant"],
["1711", "topiary duck", "plant"],
["1712", "topiary chihuahua herd", "plant"],
["1713", "topiary kiwi", "plant"],
["1714", "snake", "beast"],
["1715", "bat", "beast"],
["1716", "spider", "bug"],
["1717", "cobra", "beast"],
["1718", "tikiman", "dude"],
["1719", "scorpion", "bug"],
["1720", "bee", "bug"],
["1721", "skeleton (spelunky)", "undead"],
["1722", "yeti", "humanoid"],
["1723", "caveman", "dude"],
["1724", "alien", "humanoid"],
["1725", "alien UFO", "construct"],
["1726", "magma man", "elemental"],
["1727", "mummy", "undead"],
["1728", "crocodile man", "dude"],
["1729", "cultist", "dude"],
["1730", "vampire", "undead"],
["1731", "devil", "demon"],
["1732", "spider queen", "bug"],
["1733", "queen bee", "bug"],
["1734", "alien queen", "weird"],
["1735", "Bananubis", "beast"],
["1736", "LOLmec", "construct"],
["1737", "Yomama", "dude"],
["1738", "shopkeeper", "dude"],
["1739", "ghost (Spelunky)", "undead"],
["1740", "warehouse guard", "dude"],
["1741", "warehouse janitor", "dude"],
["1742", "warehouse clerk", "dude"],
["1743", "swarm of skulls", "undead"],
["1744", "factory-irregular skeleton", "undead"],
["1745", "remaindered skeleton", "undead"],
["1746", "novelty tropical skeleton", "undead"],
["1747", "cr&ecirc;ep", "construct"],
["1748", "baguette lady", "construct"],
["1749", "dinner troll", "construct"],
["1750", "gingerbread murderer", "construct"],
["1751", "cooler wino", "hobo"],
["1752", "sewer snake with a sewer snake in it", "beast"],
["1753", "dire pigeon", "beast"],
["1754", "malt liquor golem", "construct"],
["1755", "the former owner of the Skeleton Store", "undead"],
["1756", "Cake Lord", "construct"],
["1757", "Lot's Wife", "beast"],
["1758", "angry tourist", "dude"],
["1759", "horrible tourist family", "dude"],
["1760", "garbage tourist", "elemental"],
["1761", "filthy pirate", "pirate"],
["1762", "funky pirate", "pirate"],
["1763", "fishy pirate", "pirate"],
["1764", "flashy pirate", "construct"],
["1765", "toxic beastie", "slime"],
["1766", "Cbzzter the Grisly Bear", "construct"],
["1767", "Skeezy the Jug Rat", "construct"],
["1768", "Gurgle the Turgle", "construct"],
["1769", "nasty bear", "beast"],
["1770", "Wart Dinsey", "construct"],
["1771", "Lovestruck Tropical Honeymooners", "dude"],
["1772", "Drunken Tropical Vacationer", "dude"],
["1773", "Resort Waiter", "dude"],
["1774", "Brick Mulligan, the Bartender", "dude"],
["1775", "The Unknown Seal Clubber", "undead"],
["1776", "The Unknown Turtle Tamer", "undead"],
["1777", "The Unknown Pastamancer", "undead"],
["1778", "The Unknown Sauceror", "undead"],
["1779", "The Unknown Disco Bandit", "undead"],
["1780", "The Unknown Accordion Thief", "undead"],
["1781", "Hermit (monster)", "dude"],
["1782", "The Emperor", "dude"],
["1783", "legal alien", "humanoid"],
["1784", "mine worker (female)", "dude"],
["1785", "mine overseer (male)", "dude"],
["1786", "mine worker (male)", "dude"],
["1787", "mine overseer (female)", "dude"],
["1788", "healing crystal golem", "construct"],
["1789", "factory worker (female)", "dude"],
["1790", "factory overseer (male)", "dude"],
["1791", "factory overseer (female)", "dude"],
["1792", "factory worker (male)", "dude"],
["1793", "lava golem", "construct"],
["1794", "SMOOCH private", "dude"],
["1795", "SMOOCH sergeant", "dude"],
["1796", "SMOOCH general", "dude"],
["1797", "lava lamprey", "fish"],
["1798", "lavatory", "elemental"],
["1799", "basaltamander", "beast"],
["1800", "angry mushroom guy", "plant"],
["1801", "freaked-out mushroom guy", "plant"],
["1802", "muscular mushroom guy", "plant"],
["1803", "armored mushroom guy", "plant"],
["1804", "wizardly mushroom guy", "plant"],
["1805", "fiery mushroom guy", "plant"],
["1806", "dancing mushroom guy", "plant"],
["1807", "wailing mushroom guy", "plant"],
["1814", "Mr. Choch", "dude"],
["1815", "Mr. Cheeng", "dude"],
["1816", "Travoltron", "construct"],
["1817", "Geve Smimmons", "dude"],
["1818", "Raul Stamley", "dude"],
["1819", "Pener Crisp", "dude"],
["1820", "Deuce Freshly", "dude"],
["1821", "Lavalos", "horror"],
["1840", "The Barrelmech of Diogenes", "construct"],
["1841", "Richard X", "dude"],
["1842", "Groundling", "dude"],
["1843", "Hamlet", "dude"],
["1844", "Othello", "dude"],
["1845", "Ye Olde Key Grippe", "dude"],
["1846", "Understudy", "dude"],
["1847", "ghost actor", "undead"],
["1848", "VYKEA viking (male)", "dude"],
["1849", "VYKEA viking (female)", "dude"],
["1850", "ice bartender", "dude"],
["1851", "ice porter", "dude"],
["1852", "ice concierge", "dude"],
["1853", "ice housekeeper", "dude"],
["1854", "ice clerk", "dude"],
["1855", "Tin of Submardines", "fish"],
["1856", "Norwhal", "fish"],
["1857", "Arctic Octolus", "fish"],
["1858", "X-32-F Combat Training Snowman", "construct"],
["1859", "Performer of Actions", "weird"],
["1860", "Thinker of Thoughts", "weird"],
["1861", "Perceiver of Sensations", "weird"],
["1862", "armored Crimbot", "construct"],
["1863", "sparking Crimbot", "construct"],
["1864", "unstable nuclear Crimbot", "construct"],
["1865", "common criminal", "dude"],
["1866", "uncommon criminal", "dude"],
["1867", "rare criminal", "dude"],
["1868", "low-level mook", "dude"],
["1869", "mid-level mook", "dude"],
["1870", "high-level mook", "dude"],
["1871", "Kudzu", "plant"],
["1872", "Mansquito", "dude"],
["1873", "Miss Graves", "dude"],
["1874", "The Plumber", "dude"],
["1875", "The Author", "dude"],
["1876", "The Mad Libber", "dude"],
["1877", "Doc Clock", "dude"],
["1878", "Mr. Burns", "dude"],
["1879", "The Inquisitor", "dude"],
["1880", "vine-controlled botanist", "plant"],
["1881", "vicious plant creature", "plant"],
["1882", "giant leech", "bug"],
["1883", "giant mosquito", "bug"],
["1884", "lovestruck goth dude", "dude"],
["1885", "walking skeleton", "undead"],
["1886", "liquid plumber", "construct"],
["1887", "plumber's helper", "dude"],
["1888", "former inmate", "dude"],
["1889", "former guard", "dude"],
["1890", "very adjective henchwoman", "dude"],
["1891", "very adjective henchman", "dude"],
["1892", "time bandit", "dude"],
["1893", "clockwork man", "dude"],
["1894", "serial arsonist", "dude"],
["1895", "burner", "dude"],
["1896", "inquisitee", "dude"],
["1897", "trivia researcher", "dude"],
["1898", "The Jokester", "dude"],
["1899", "drunk cowpoke", "dude"],
["1900", "surly gambler", "dude"],
["1901", "wannabe gunslinger", "dude"],
["1902", "cow cultist", "dude"],
["1903", "hired gun", "dude"],
["1904", "camp cook", "dude"],
["1905", "skeletal gunslinger", "undead"],
["1906", "restless ghost", "undead"],
["1907", "buzzard", "beast"],
["1908", "mountain lion", "beast"],
["1909", "grizzled bear", "beast"],
["1910", "diamondback rattler", "beast"],
["1911", "coal snake", "beast"],
["1912", "frontwinder", "beast"],
["1913", "caugr", "demon"],
["1914", "pyrobove", "demon"],
["1915", "spidercow", "demon"],
["1916", "moomy", "demon"],
["1917", "Jeff the Fancy Skeleton", "undead"],
["1918", "Daisy the Unclean", "demon"],
["1919", "Pecos Dave", "dude"],
["1920", "Pharaoh Amoon-Ra Cowtep", "demon"],
["1921", "Snake-Eyes Glenn", "dude"],
["1922", "Former Sheriff Dan Driscoll", "dude"],
["1923", "unusual construct", "construct"],
["1924", "Clara", "demon"],
["1925", "Granny Hackleton", "dude"],
["1926", "furious cow", "demon"],
["1927", "emaciated rodeo clown", "horror"],
["1928", "aggressive grass snake", "beast"],
["1929", "furious giant cow", "demon"],
["1930", "menacing rodeo clown", "horror"],
["1931", "prince snake", "beast"],
["1932", "ungulith", "demon"],
["1933", "grizzled rodeo clown", "horror"],
["1934", "king snake", "beast"],
["1935", "Witchess Pawn", "dude"],
["1936", "Witchess Knight", "dude"],
["1937", "Witchess Ox", "beast"],
["1938", "Witchess Rook", "construct"],
["1939", "Witchess Queen", "dude"],
["1940", "Witchess King", "dude"],
["1941", "Witchess Witch", "dude"],
["1942", "Witchess Bishop", "dude"],
["1943", "Cinco de Mayo reveler", "dude"],
["1944", "One Thousand Source Agents", "construct"],
["1945", "Source Agent", "construct"],
["1946", "the ghost of Oily McBindle", "undead"],
["1947", "boneless blobghost", "undead"],
["1948", "the ghost of Monsieur Baguelle", "undead"],
["1949", "The Headless Horseman", "undead"],
["1950", "The Icewoman", "undead"],
["1951", "The ghost of Ebenoozer Screege", "undead"],
["1952", "The ghost of Lord Montague Spookyraven", "undead"],
["1953", "The ghost of Vanillica \"Trashblossom\" Gorton", "undead"],
["1954", "The ghost of Sam McGee", "undead"],
["1955", "The ghost of Richard Cockingham", "undead"],
["1956", "The ghost of Waldo the Carpathian", "undead"],
["1957", "Emily Koops, a spooky lime", "undead"],
["1958", "The ghost of Jim Unfortunato", "undead"],
["1959", "Apathetic Tyrannosaurus", "beast"],
["1960", "Assembly Elemental", "elemental"],
["1961", "Cro-Magnon Gnoll", "humanoid"],
["1962", "Ancient Skeleton with Skin still on it", "undead"],
["1963", "Wooly Duck", "beast"],
["1964", "Krakrox the Barbarian (monster)", "dude"],
["1965", "time-spinner prank", "dude"],
["1967", "board games elemental", "construct"],
["1968", "nerd rapper", "dude"],
["1969", "stumbling-drunk congoer (male)", "dude"],
["1970", "swimming pool monster", "elemental"],
["1971", "Arizona bark scorpion", "bug"],
["1972", "stumbling-drunk congoer (female)", "dude"],
["1973", "Thanksgolem", "construct"],
["1974", "Eldritch Tentacle", "horror"],
["1975", "gingerbread pigeon", "beast"],
["1976", "gingerbread rat", "beast"],
["1977", "gingerbread convict", "dude"],
["1978", "gingerbread mad dog", "beast"],
["1979", "gingerbread lawyer", "dude"],
["1980", "gingerbread vagrant", "dude"],
["1981", "animal cracker", "beast"],
["1982", "gingerbread wino", "dude"],
["1983", "gingerbread mugger", "dude"],
["1984", "gingerbread welder robot", "construct"],
["1985", "gingerbread mutant", "dude"],
["1986", "gingerbread gentrifier", "dude"],
["1987", "gingerbread finance bro", "dude"],
["1988", "gingerbread tech bro", "dude"],
["1989", "gingerbread alligator", "beast"],
["1990", "gingerbread vigilante", "dude"],
["1991", "Judge Fudge", "dude"],
["1992", "GNG-3-R", "construct"],
["1993", "obsessively imagining your worst phobias", "weird"],
["1994", "the realization that everyone you love will die someday", "weird"],
["1995", "imagining how your life would be better if you'd made different decisions", "weird"],
["1996", "fear of an uncertain future", "weird"],
["1997", "that time you screwed everything up like a complete idiot", "weird"],
["1998", "the most embarrassing moment in your entire life", "weird"],
["1999", "what you totally should have said that one time", "weird"],
["2000", "endless winter", "weird"],
["2001", "the abstract concept of poverty", "weird"],
["2002", "angry viking warriors", "weird"],
["2003", "bottle of cheap whiskey", "weird"],
["2004", "the Crimborg", "weird"],
["2005", "penguin mafioso", "weird"],
["2006", "simple hobo", "weird"],
["2007", "Your Brain", "weird"],
["2008", "The Krampus", "weird"],
["2009", "LOV Enforcer", "dude"],
["2010", "LOV Engineer", "dude"],
["2011", "LOV Equivocator", "dude"],
["2012", "Sssshhsssblllrrggghsssssggggrrgglsssshhssslblgl", "horror"],
["2013", "hostile plant", "plant"],
["2014", "large hostile plant", "plant"],
["2015", "exotic hostile plant", "plant"],
["2016", "small hostile animal", "beast"],
["2017", "large hostile animal", "beast"],
["2018", "exotic hostile animal", "beast"],
["2019", "Spant drone", "bug"],
["2020", "Spant soldier", "bug"],
["2021", "Murderbot drone", "construct"],
["2022", "Murderbot soldier", "construct"],
["2023", "hostile intelligent alien", "humanoid"],
["2024", "Villainous Minion", "dude"],
["2025", "Villainous Henchperson", "dude"],
["2026", "Villainous Villain", "dude"],
["2028", "Blofeld", "dude"],
["2029", "Genie", "elemental"],
["2031", "Mob Penguin union rail worker", "penguin"],
["2032", "amorphous blob", "slime"],
["2033", "giant amorphous blob", "slime"],
["2034", "Mob Penguin protector", "penguin"],
["2035", "Mob Penguin steel driver", "penguin"],
["2036", "Mob Penguin negotiator", "penguin"],
["2037", "Mob Penguin organizer", "penguin"],
["2041", "voiceless whisper", "weird"],
["2042", "silent scream", "weird"],
["2043", "mouthless murmur", "weird"],
["2044", "cheerless mime functionary", "horror"],
["2045", "cheerless mime scientist", "horror"],
["2046", "cheerless mime soldier", "horror"],
["2047", "cheerless mime vizier", "horror"],
["2048", "cheerless mime executive", "horror"],
["2049", "The Silent Nightmare", "horror"],
["2050", "Jerry Bradford (Boss Bat)", "dude"],
["2051", "Jerry Bradford (Knob Goblin King)", "dude"],
["2052", "Jerry Bradford (Bonerdagon)", "dude"],
["2053", "Jerry Bradford (Groar)", "dude"],
["2054", "Jerry Bradford (Dr. Awkward)", "dude"],
["2055", "Jerry Bradford (Lord Spookyraven)", "dude"],
["2056", "Jerry Bradford (Protector Spectre)", "dude"],
["2057", "Jerry Bradford (The Big Wisniewski)", "dude"],
["2058", "Jerry Bradford (The Man)", "dude"],
["2059", "Jerry Bradford, Pokéfam World Champion", "dude"],
["2060", "fantasy bandit", "dude"],
["2061", "fantasy ourk", "dude"],
["2062", "fantasy forest faerie", "dude"],
["2063", "swamp monster", "dude"],
["2064", "cursed villager", "dude"],
["2065", "Spooky ghost (FantasyRealm)", "dude"],
["2066", "tree hugging hippy protestor", "hippy"],
["2067", "mining grobold", "construct"],
["2068", "rubber bat", "construct"],
["2069", "quadfaerie", "construct"],
["2070", "druid plants", "plant"],
["2071", "flock of every birds", "beast"],
["2072", "plywood cultists", "construct"],
["2073", "barrow wraith", "construct"],
["2074", "regular thief", "dude"],
["2075", "swamp troll", "construct"],
["2076", "crypt creeper", "construct"],
["2077", "Phoenix", "elemental"],
["2078", "Sewage Treatment Dragon", "construct"],
["2079", "Duke Vampire", "construct"],
["2080", "Spider Queen", "dude"],
["2081", "Archwizard", "dude"],
["2082", "Ley Incursion", "elemental"],
["2083", "Ghoul King", "humanoid"],
["2084", "Ogre Chieftain", "humanoid"],
["2085", "Ted Schwartz, Master Thief", "dude"],
["2086", "tree loving hippy protestor", "hippy"],
["2087", "Skeleton Lord", "construct"],
["2088", "God Lobster (monster)", "horror"],
["2089", "biker", "dude"],
["2090", "plain girl", "dude"],
["2091", "jock", "dude"],
["2092", "party girl", "dude"],
["2093", "burnout", "dude"],
["2094", "angry ghost", "undead"],
["2095", "government bureaucrat", "dude"],
["2096", "terrible mutant", "humanoid"],
["2097", "slime blob", "slime"],
["2098", "annoyed snake", "beast"],
["2099", "wild walrus", "beast"],
["2100", "herd of wild lemmings", "beast"],
["2101", "wild moose", "beast"],
["2102", "wild beaver", "beast"],
["2103", "wild reindeer", "beast"],
["2104", "sausage goblin", "goblin"],
["2105", "Steve Belmont", "dude"],
["2106", "Ricardo Belmont", "dude"],
["2107", "Jayden Belmont", "dude"],
["2108", "Travis Belmont", "dude"],
["2109", "Greg Dagreasy", "dude"],
["2110", "Sylvia Belgrande", "dude"],
["2111", "Sharona", "dude"],
["2112", "Jake Norris", "dude"],
["2113", "Chad Alacarte", "dude"],
["2114", "%alucard%", "dude"],
["2115", "Your Lack of Reflection", "horror"],
["2116", "giant crab", "beast"],
["2117", "melty army man", "dude"],
["2118", "plastic skeleton", "undead"],
["2119", "plastic pirate", "construct"],
["2120", "translucent monkey", "beast"],
["2121", "giant giant crab", "beast"],
["2122", "blind snake", "beast"],
["2123", "toy dinosaur", "beast"],
["2124", "cockroach", "bug"],
["2125", "vape ghost", "undead"],
["2126", "signal", "weird"],
["2127", "tiki idol", "construct"],
["2128", "pewter torsohunter", "construct"],
["2129", "carnivorous plant", "plant"],
["2130", "strong wind", "weird"],
["2131", "jungle titan", "dude"],
["2132", "pirate radio", "construct"],
["2133", "melty freezeface", "construct"],
["2134", "Red Roger", "construct"],
["2135", "Glass Jack Hummel", "construct"],
["2136", "skeleton astronaut", "undead"],
["2137", "invader bullet", "construct"],
["2138", "the invader", "construct"],
["2140", "%monster%", "construct"],
["2141", "gingerbread maw", "horror"],
["2142", "nutmeg anemone", "plant"],
["2143", "icingfish", "fish"],
["2144", "Mer-kin baker", "mer-kin"],
["2145", "dolphin \"orphan\"", "fish"],
["2146", "kelpie (horse form)", "beast"],
["2147", "kelpie (lady form)", "dude"],
["2148", "Crimbylow", "demon"],
["2149", "sea-elf", "elf"],
["2150", "peppermint eel", "fish"],
["2151", "Yuleviathan", "fish"],
["2152", "Dolph Bossin, the Boss Dolphin", "fish"],
["2153", "basic lihc", "undead"],
["2154", "party skelteon", "undead"],
["2155", "musical fruit bat", "beast"],
["2156", "magical fruit bat", "beast"],
["2162", "drippy tree", "plant"],
["2163", "drippy bat", "beast"],
["2164", "The Thing in the Basement", "horror"],
["2165", "Koopa Paratroopa", "beast"],
["2166", "Hammer Brother", "beast"],
["2167", "Very Dry Bones", "undead"],
["2168", "Birdo", "beast"],
["2169", "King Boo", "undead"],
["2170", "Kamek", "beast"],
["2171", "Angry Sun", "weird"],
["2172", "Bowser (Hippy Camp)", "beast"],
["2173", "Bowser (Orcish Frat House)", "beast"],
["2174", "Wa%playername/lowercase%", "dude"],
["2175", "piranha plant", "plant"],
["2176", "drippy reveler", "humanoid"],
["2177", "grey goo orb", "construct"],
["2178", "grey goo torus", "construct"],
["2179", "grey goo triangle", "construct"],
["2180", "grey goo hexagon", "construct"],
["2181", "grey goo square", "construct"],
["2182", "grey goo cross", "construct"],
["2183", "grey goo heart", "construct"],
["2184", "grey goo hourglass", "construct"],
["2185", "grey goo octagon", "construct"],
["2186", "grey goo squiggle", "construct"],
["2187", "grey goo star", "construct"],
["2188", "goo clown", "construct"],
["2189", "grey gooblin", "construct"],
["2190", "grey goo bat", "construct"],
["2191", "goo-covered beanstalk segment", "construct"],
["2192", "goog", "construct"],
["2193", "a massive prism of grey goo", "construct"],
["2194", "goo bone", "construct"],
["2195", "goo grid", "construct"],
["2196", "Burning Daughter", "elemental"],
["2197", "Herald of Fridgr", "dude"],
["2198", "Tentacle of Sssshhsssblllrrggghsssssggggrrgglsssshhssslblgl", "horror"],
["2199", "Chosen of Yog-Urt", "horror"],
["2200", "Astrologer of Shub-Jigguwatt", "constellation"],
["2201", "Boss Bot", "construct"],
["2202", "Gobot King", "construct"],
["2203", "Robonerdagon", "construct"],
["2204", "Tobias J. Saibot", "construct"],
["2205", "Lord Cyberraven", "construct"],
["2206", "Protector S. P. E. C. T. R. E.", "construct"],
["2207", "Groarbot", "construct"],
["2208", "The Artificial Wisniewski", "construct"],
["2209", "The Android", "construct"],
["2210", "Nautomatic Sorceress", "construct"],
["2211", "Blaze Bat", "beast"],
["2212", "fired-up Knob Goblin King", "goblin"],
["2213", "Burnerdagon", "undead"],
["2214", "Dr. Awkward, who is on fire", "dude"],
["2215", "Lord Sootyraven", "undead"],
["2216", "Protector Spectre (Wildfire)", "undead"],
["2217", "Groar, Except Hot", "beast"],
["2218", "The Big Ignatowicz", "hippy"],
["2219", "The Man on Fire", "dude"],
["2220", "The Naughty Scorcheress", "dude"],
["2221", "gooified elf-thing", "elf"],
["2222", "gooified dog-thing", "beast"],
["2223", "gooified flower", "plant"],
["2224", "gooified tree", "plant"],
["2225", "gooified rock slab", "elemental"],
["2226", "massive goo construct", "construct"],
["2227", "void slab", "horror"],
["2228", "void spider", "horror"],
["2229", "void guy", "horror"],
["2230", "kachungasaur", "beast"],
["2231", "dilophosaur", "beast"],
["2232", "high-altitude pterodactyl", "beast"],
["2233", "glass-shelled archelon", "beast"],
["2234", "supersonic velociraptor", "beast"],
["2235", "spikolodon", "beast"],
["2236", "ghostasaurus", "undead"],
["2237", "flatusaurus", "beast"],
["2238", "primitive chicken", "beast"],
["2239", "two-headed pteranodon with a two-headed bat inside it", "beast"],
["2240", "goblodocus", "beast"],
["2241", "T-Rex who ate the Bonerdagon", "beast"],
["2242", "suruasaurus", "beast"],
["2243", "herd of well-fed microraptors", "beast"],
["2244", "protoceratops spectre", "undead"],
["2245", "refrigeradon", "beast"],
["2246", "Slackiosaurus", "beast"],
["2247", "Oligarcheopteryx", "beast"],
["2248", "Naughty Saursaurus", "beast"],
["2249", "gator-human hybrid", "beast"],
["2250", "gangster's moll", "dude"],
["2251", "traveling hobo", "hobo"],
["2252", "goblin flapper", "goblin"],
["2253", "undercover prohibition agent", "dude"],
["2254", "Brake-Operating Trainbot", "construct"],
["2255", "Track-Switching Trainbot", "construct"],
["2256", "Ping-Pong-Playing Trainbot", "construct"],
["2257", "Drink-Delivery Trainbot", "construct"],
["2258", "Luggage-Handling Trainbot", "construct"],
["2259", "Ticket-Checking Trainbot", "construct"],
["2260", "Table-Waiting Trainbot", "construct"],
["2261", "Wine-Pairing Trainbot", "construct"],
["2262", "Table-Bussing Trainbot", "construct"],
["2263", "Coal-Shoveling Trainbot", "construct"],
["2264", "Slag-Processing Trainbot", "construct"],
["2265", "Steam-Routing Trainbot", "construct"],
["2266", "The Superconductor", "construct"],
["2267", "Moleman", "humanoid"],
["2268", "Met", "construct"],
["2269", "Tackle Fire", "construct"],
["2270", "Blader", "construct"],
["2271", "shadow bat", "horror"],
["2272", "shadow cow", "horror"],
["2273", "shadow devil", "horror"],
["2274", "shadow guy", "horror"],
["2275", "shadow hexagon", "horror"],
["2276", "shadow orb", "horror"],
["2277", "shadow prism", "horror"],
["2278", "shadow slab", "horror"],
["2279", "shadow snake", "horror"],
["2280", "shadow spider", "horror"],
["2281", "shadow stalk", "horror"],
["2282", "shadow tree", "horror"],
["2283", "two-headed shadow bat", "horror"],
["2284", "goblin king's shadow", "horror"],
["2285", "shadowboner shadowdagon", "horror"],
["2286", "W. Odah's Shadow", "horror"],
["2287", "shadow Lord Spookyraven", "horror"],
["2288", "corruptor shadow", "horror"],
["2289", "shadow of groar", "horror"],
["2290", "shadow of the 1960s", "horror"],
["2291", "shadow of the 1980s", "horror"],
["2292", "General Bruise", "horror"],
["2293", "General Bruise (true form)", "horror"],
["2294", "Dark Noël", "horror"],
["2295", "Dark Noël (true form)", "horror"],
["2296", "Terrence Poindexter", "horror"],
["2297", "Terrence Poindexter (true form)", "horror"],
["2298", "shadow spire", "horror"],
["2299", "shadow orrery", "horror"],
["2300", "shadow tongue", "horror"],
["2301", "shadow scythe", "horror"],
["2302", "shadow cauldron", "horror"],
["2303", "shadow matrix", "horror"],
["2316", "Classic Boss Bat", "beast"],
["2317", "Weirdly Scrawny Knob Goblin King", "goblin"],
["2318", "Orignial Bonerdagon", "undead"],
["2319", "Jr. Awkwarj", "dude"],
["2320", "Little Lord Spookyraven", "undead"],
["2321", "Protector Spectre Candidate", "undead"],
["2322", "Flock of Groars?", "beast"],
["2323", "The Little Wisniewski", "hippy"],
["2324", "The Boy", "dude"],
["2325", "ncle", "bug"],
["2326", "rutabaga bug", "bug"],
["2327", "mesquito", "bug"],
["2328", "senate fly", "bug"],
["2329", "flagellating mantis", "bug"],
["2330", "beetle", "bug"],
["2331", "terrorantula", "bug"],
["2332", "daddy shortlegs", "bug"],
["2333", "birdybug", "bug"],
["2334", "kilopede", "bug"],
["2336", "Tooth Golem", "construct"]];

$classes = [
	["Seal Clubber", "1"],
	["Turtle Tamer", "2"],
	["Pastamancer", "3"],
	["Sauceror", "4"],
	["Disco Bandit", "5"],
	["Accordion Thief", "6"],
	["Avatar of Boris", "11"],
	["Zombie Master", "12"],
	["Avatar of Jarlsberg", "14"],
	["Avatar of Sneaky Pete", "15"],
	["Ed the Undying", "17"],
	["Cow Puncher", "18"],
	["Bean Slinger", "19"],
	["Snake Oiler", "20"],
	["Gelatinous Noob", "23"],
	["Vampyre", "24"],
	["Plumber", "25"],
	["Grey You", "27"],
	["Pig Skinner", "28"],
	["Cheese Wizard", "29"],
	["Jazz Agent", "30"],
];

$paths = [
	["Bad Moon", "0"],
	["Unrestricted/None", "0"],
	["Boozetafarian", "1"],
	["Teetotaler", "2"],
	["Oxygenarian", "3"],
	["Bees Hate You", "4"],
	["Way of the Surprising Fist", "6"],
	["Trendy", "7"],
	["Avatar of Boris", "8"],
	["Bugbear Invasion", "9"],
	["Zombie Slayer", "10"],
	["Class Act", "11"],
	["Avatar of Jarlsberg", "12"],
	["BIG!", "14"],
	["KOLHS", "15"],
	["Class Act II: A Class For Pigs", "16"],
	["Avatar of Sneaky Pete", "17"],
	["Slow and Steady", "18"],
	["Heavy Rains", "19"],
	["Picky", "21"],
	["Standard", "22"],
	["Actually Ed the Undying", "23"],
	["One Crazy Random Summer", "24"],
	["Community Service", "25"],
	["Avatar of West of Loathing", "26"],
	["The Source", "27"],
	["Nuclear Autumn", "28"],
	["Gelatinous Noob", "29"],
	["License to Adventure", "30"],
	["Live. Ascend. Repeat.", "31"],
	["Pocket Familiars", "32"],
	["G-Lover", "33"],
	["Disguises Delimit", "34"],
	["Dark Gyffte", "35"],
	["Two Crazy Random Summer", "36"],
	["Kingdom of Exploathing", "37"],
	["Path of the Plumber", "38"],
	["Low Key Summer", "39"],
	["Grey Goo", "40"],
	["You, Robot", "41"],
	["Quantum Terrarium", "42"],
	["Wildfire", "43"],
	["Grey You", "44"],
	["Journeyman", "45"],
	["Fall of the Dinosaurs", "46"],
	["Avatar of Shadows Over Loathing", "47"],
	["Legacy of Loathing", "48"],
	["A Shrunken Adventurer Am I", "49"]
];

$regular_effects = [
	"+Muscle substats",
    "+Moxie substats",
    "+Mysticality substats",
    "Restore HP (10%)",
    "Restore MP (10%)",
    "+1 familiar experience",
    "+25% item drop bonus",
    "It's a mystery (I Refuse!)",
    "Antiantifrozen (+3 <span style='color: red'>hot</span> resistance, 10 turns)",
    "Shamed (+3 <span style='color: purple'>sleaze</span> resistance, 10 turns)",
    "Disabled Olfactory Processing (+3 <span style='color: green'>stench</span> resistance, 10 turns)",
    "Imagining Guts (+3 <span style='color: blue'>cold</span> resistance, 10 turns)",
    "Spooked (+3 <span style='color: gray'>spooky</span> resistance, 10 turns)",
    "Ultrahydrated (5 turns)",
    "worthless item",
    "some Meat",
    "pocket wish (cap 3/day)",
    "fat stacks of cash",
    "Sweet and Red / Green / Yellow",
    "Gummi Heart / Brain / Skin",
    "Ooh, Sweet! / Salty! / Bitter! / Sour! / Umami!",
];

$phylum_effects = [
	"beast" => [
		"Egg-stra Arm / Egg-cellent Vocabulary / Egg-stortionary Tactics / Eggs-tra Sensory Perception / Egg-headedness",
		"displaced fish",
		"long pork"
	],
	"bug" => [
		"Feeling Excited (15 turns)",
		"Feeling Excited (15 turns)",
		"Industrial Strength Starch (15 turns)",
		"filet of tangy gnat (\"fotelif\")"
	],
	"constellation" => [
		"3 stars",
		"alien drugs",
		"3 lines"
	],
	"construct" => [
		"a mechanical part (flange / cog / spring / clockwork key / sprocket)",
		"Armor-Plated (20 turns)",
		"Restore MP (20%)"
	],
	"demon" => [
		"fire",
		"hot powder"
	],
	"dude" => [
		"a skull (broken or smart)",
		"gob of wet hair",
		"Feeling Excited (15 turns)"
	],
	"elemental" => [
		"cold powder",
		"twinkly nuggets",
		"+all substats"
	],
	"elf" => [
		"candy cane",
		"+Moxie substats",
		"bottle of whiskey"
	],
	"fish" => [
		"Fishy (10 turns)",
		"fish meat (slick / glistening / beefy)",
		"3 dull fish scales"
	],
	"goblin" => [
		"Knob mushroom",
		"bowl of cottage cheese",
		"Cobb's Knob Wurstbrau"
	],
	"hippy" => [
		"a fruit",
		"stench powder",
		"pretty flower"
	],
	"hobo" => [
		"bottle of vodka",
		"hobo nickel",
		"+Moxie substats"
	],
	"horror" => [
		"thin black candle",
		"Restore HP (20%)",
		"scroll of ancient forbidden unspeakable evil"
	],
	"humanoid" => [
		"+Muscle substats",
		"fine wine"
	],
	"mer-kin" => [
		"+Mysticality substats",
		"fish meat (slick / glistening / beefy)",
		"seaweed"
	],
	"orc" => [
		"sleaze powder",
		"tattered scrap of paper (cap 11/day)",
		"bottle of tequila"
	],
	"penguin" => [
		"magical ice cubes",
		"+Muscle substats",
		"some Meat"
	],
	"pirate" => [
		"bottle of rum",
		"+Moxie substats",
		"eyepatch"
	],
	"plant" => [
		"cherry",
		"Restore HP (50%)",
		"+all substats"
	],
	"slime" => [
		"+all substats",
		"+Moxie substats",
		"Slimed (20)"
	],
	"undead" => [
		"skeleton bone",
		"spooky powder",
		"+Mysticality substats"
	],
	"weird" => [
		"+Mysticality substats",
		"Restore MP (25%)",
		"a feather (frozen / fetid / flirtatious / flaming / frightful)"
	]
];

function get_bofa_kill_effect($class_id, $path_id, $monster) {
	global $phylum_effects, $regular_effects;
	$seed = 421 * $class_id + 11 * $path_id + (int)$monster[0];
	mt_srand($seed, MT_RAND_PHP);
	$effect = null;
	if ($seed % 3 == 1) {
		$effect = $phylum_effects[$monster[2]][mt_rand(0, count($phylum_effects[$monster[2]]) - 1)];
	}
	else {
		$effect = $regular_effects[mt_rand(0, count($regular_effects) - 1)];
	}
	return $effect;
}